/**
 * Strings for the Account area (Segment 1 of the accounts roadmap): the
 * More screen's Account section, sign-in/sign-up, username claiming, and
 * profile management. No old-MVP equivalent to port from — this app never
 * had accounts before now, so this copy is new, written to match this
 * catalogue's existing voice.
 */

export const accountStrings = {
  en: {
    more: {
      heading: 'ACCOUNT',
      guestTitle: "You're browsing as a guest",
      guestBody: 'Nothing you do is stored beyond this device. Create an Alias to save your journal to the cloud, join the community map, and more.',
      signIn: 'Sign In',
      createAlias: 'Create an Alias',
      manageProfile: 'Manage Profile',
      signOut: 'Sign Out',
      finishSetupTitle: 'Finish setting up your Alias',
      finishSetupBody: 'Choose a username to start using your Alias.',
    },
    signIn: {
      title: 'Sign In',
      subtitle: 'Welcome back.',
      email: 'Email',
      emailPlaceholder: 'you@example.com',
      password: 'Password',
      passwordPlaceholder: '••••••••',
      submit: 'Sign In',
      or: 'or',
      google: 'Continue with Google',
      noAccount: "Don't have an Alias?",
      createOne: 'Create one',
    },
    signUp: {
      title: 'Create an Alias',
      subtitle: 'No real name, ever — just an email and a username only you choose.',
      email: 'Email',
      emailPlaceholder: 'you@example.com',
      password: 'Password',
      passwordPlaceholder: 'At least 6 characters',
      submit: 'Create Alias',
      or: 'or',
      google: 'Continue with Google',
      haveAccount: 'Already have an Alias?',
      signInInstead: 'Sign in',
      checkEmailTitle: 'Check your email',
      checkEmailBody: "We've sent a confirmation link. Tap it, then come back and sign in.",
      backToSignIn: 'Back to Sign In',
    },
    username: {
      title: 'Choose a Username',
      subtitle: "This is how you'll appear everywhere in Houna — never your real name.",
      placeholder: 'username',
      checking: 'Checking availability…',
      available: 'Available',
      taken: 'Already taken',
      invalid: '3–20 characters — letters, numbers, and underscore only',
      submit: 'Continue',
    },
    profile: {
      title: 'Profile',
      username: 'Username',
      avatar: 'Avatar',
      changePhoto: 'Change Photo',
      country: 'Country',
      selectCountry: 'Select your country',
      gccGroup: 'Gulf Countries',
      allCountries: 'All Countries',
      communityMap: 'Community Map',
      signOut: 'Sign Out',
      signOutConfirmTitle: 'Sign out?',
      signOutConfirmBody: "You'll need your email and password (or Google) to sign back in.",
      cancel: 'Cancel',
    },
    community: {
      title: 'Community Map',
      subtitle: "Where Houna's community is breathing from, tap a dot for the country's name.",
      loading: 'Loading…',
      error: 'Unable to load the map right now.',
      empty: 'No one has set a country yet — be the first.',
      totalLabel: 'Alias members with a country set',
      countriesLabel: 'Countries represented',
    },
    notifications: {
      title: 'Notifications',
      subtitle: 'Choose what Houna can remind you about.',
      reminderTitle: 'Daily Reminder',
      reminderBody: 'A gentle nudge once a day to take a moment for yourself.',
      reminderNotificationTitle: 'Take a moment for yourself',
      reminderNotificationBody: 'A few minutes of breathing or meditation can help.',
      permissionDenied: "Notifications are off in your device settings — Houna can't schedule this until you allow them.",
      remoteHeading: 'FOR YOUR ALIAS',
      storyHighlightsTitle: 'Story Highlights',
      storyHighlightsBody: "Get notified when a new Story of the Week is featured.",
      communityStatsTitle: 'Community Stats',
      communityStatsBody: 'Occasional updates on community milestones.',
      guestNote: 'Sign in with your Alias to also get story and community highlights.',
      signIn: 'Sign In',
    },
    errors: {
      email_in_use: 'That email already has an Alias — try signing in instead.',
      weak_password: 'Password must be at least 6 characters.',
      invalid_email: "That doesn't look like a valid email address.",
      invalid_credentials: 'Incorrect email or password.',
      username_taken: 'That username is already taken.',
      invalid_username: '3–20 characters — letters, numbers, and underscore only.',
      cancelled: '',
      unknown: 'Something went wrong — please try again.',
    },
  },
  ar: {
    more: {
      heading: 'الحساب',
      guestTitle: 'أنت تتصفح كزائر',
      guestBody: 'كل ما تفعله لا يُخزَّن إلا على هذا الجهاز. أنشئ اسمًا مستعارًا لحفظ يومياتك في السحابة، والانضمام لخريطة المجتمع، والمزيد.',
      signIn: 'تسجيل الدخول',
      createAlias: 'إنشاء اسم مستعار',
      manageProfile: 'إدارة الملف الشخصي',
      signOut: 'تسجيل الخروج',
      finishSetupTitle: 'أكمل إعداد اسمك المستعار',
      finishSetupBody: 'اختر اسم مستخدم لتبدأ استخدام اسمك المستعار.',
    },
    signIn: {
      title: 'تسجيل الدخول',
      subtitle: 'أهلاً بعودتك.',
      email: 'البريد الإلكتروني',
      emailPlaceholder: 'you@example.com',
      password: 'كلمة المرور',
      passwordPlaceholder: '••••••••',
      submit: 'تسجيل الدخول',
      or: 'أو',
      google: 'المتابعة عبر جوجل',
      noAccount: 'ليس لديك اسم مستعار؟',
      createOne: 'أنشئ واحدًا',
    },
    signUp: {
      title: 'إنشاء اسم مستعار',
      subtitle: 'بلا اسم حقيقي أبدًا — فقط بريد إلكتروني واسم مستخدم تختاره بنفسك.',
      email: 'البريد الإلكتروني',
      emailPlaceholder: 'you@example.com',
      password: 'كلمة المرور',
      passwordPlaceholder: '6 أحرف على الأقل',
      submit: 'إنشاء الاسم المستعار',
      or: 'أو',
      google: 'المتابعة عبر جوجل',
      haveAccount: 'لديك اسم مستعار بالفعل؟',
      signInInstead: 'تسجيل الدخول',
      checkEmailTitle: 'تحقق من بريدك الإلكتروني',
      checkEmailBody: 'أرسلنا رابط تأكيد. اضغط عليه ثم عد وسجّل الدخول.',
      backToSignIn: 'العودة لتسجيل الدخول',
    },
    username: {
      title: 'اختر اسم مستخدم',
      subtitle: 'هكذا ستظهر في كل مكان في هُنا — وليس باسمك الحقيقي أبدًا.',
      placeholder: 'اسم المستخدم',
      checking: 'جاري التحقق من التوفر…',
      available: 'متوفر',
      taken: 'مُستخدم بالفعل',
      invalid: '٣–٢٠ حرفًا — أحرف إنجليزية وأرقام وشرطة سفلية فقط',
      submit: 'متابعة',
    },
    profile: {
      title: 'الملف الشخصي',
      username: 'اسم المستخدم',
      avatar: 'الصورة الرمزية',
      changePhoto: 'تغيير الصورة',
      country: 'الدولة',
      selectCountry: 'اختر دولتك',
      gccGroup: 'دول الخليج',
      allCountries: 'كل الدول',
      communityMap: 'خريطة المجتمع',
      signOut: 'تسجيل الخروج',
      signOutConfirmTitle: 'تسجيل الخروج؟',
      signOutConfirmBody: 'ستحتاج بريدك الإلكتروني وكلمة المرور (أو جوجل) لتسجيل الدخول مرة أخرى.',
      cancel: 'إلغاء',
    },
    community: {
      title: 'خريطة المجتمع',
      subtitle: 'من أين يتنفّس مجتمع هُنا، اضغط على نقطة لمعرفة اسم الدولة.',
      loading: 'جاري التحميل…',
      error: 'تعذّر تحميل الخريطة الآن.',
      empty: 'لم يحدد أحد دولته بعد — كن أول من يفعل.',
      totalLabel: 'الأعضاء الذين حددوا دولتهم',
      countriesLabel: 'عدد الدول الممثّلة',
    },
    notifications: {
      title: 'الإشعارات',
      subtitle: 'اختر بما يمكن لهُنا تذكيرك.',
      reminderTitle: 'تذكير يومي',
      reminderBody: 'تذكير لطيف مرة يوميًا لأخذ لحظة لنفسك.',
      reminderNotificationTitle: 'خذ لحظة لنفسك',
      reminderNotificationBody: 'بضع دقائق من التنفس أو التأمل قد تساعدك.',
      permissionDenied: 'الإشعارات مغلقة في إعدادات جهازك — لا يمكن لهُنا جدولة هذا حتى تسمح بها.',
      remoteHeading: 'لاسمك المستعار',
      storyHighlightsTitle: 'قصص مميزة',
      storyHighlightsBody: 'احصل على إشعار عند نشر قصة أسبوعية جديدة.',
      communityStatsTitle: 'إحصائيات المجتمع',
      communityStatsBody: 'تحديثات بين حين وآخر عن إنجازات المجتمع.',
      guestNote: 'سجّل الدخول باسمك المستعار للحصول أيضًا على القصص المميزة وتحديثات المجتمع.',
      signIn: 'تسجيل الدخول',
    },
    errors: {
      email_in_use: 'هذا البريد الإلكتروني لديه اسم مستعار بالفعل — جرّب تسجيل الدخول بدلاً من ذلك.',
      weak_password: 'يجب ألا تقل كلمة المرور عن 6 أحرف.',
      invalid_email: 'هذا لا يبدو بريدًا إلكترونيًا صالحًا.',
      invalid_credentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
      username_taken: 'اسم المستخدم هذا مُستخدم بالفعل.',
      invalid_username: '٣–٢٠ حرفًا — أحرف إنجليزية وأرقام وشرطة سفلية فقط.',
      cancelled: '',
      unknown: 'حدث خطأ ما — يرجى المحاولة مرة أخرى.',
    },
  },
};
