/**
 * Strings for the Account area (Segment 1 of the accounts roadmap): the
 * More screen's Account section, sign-in/sign-up, username claiming, and
 * profile management. No old-MVP equivalent to port from — this app never
 * had accounts before now, so this copy is new, written to match this
 * catalogue's existing voice.
 */

export const accountStrings = {
  en: {
    eyebrow: 'Account',
    more: {
      heading: 'ACCOUNT',
      guestTitle: "You're browsing as a guest",
      guestBody: 'Nothing you do is stored beyond this device. Create an Alias to save your journal to the cloud, join the community map, and more.',
      signIn: 'Sign In',
      createAlias: 'Create an Alias',
      manageProfile: 'Manage Profile',
      signOut: 'Sign Out',
      finishSetupTitle: 'Finish setting up your Alias',
      finishSetupBody: 'Choose a username to start using your Alias.',
    },
    signIn: {
      title: 'Welcome back',
      subtitle: 'Sign in to your Alias to pick up where you left off.',
      email: 'Email',
      emailPlaceholder: 'you@example.com',
      password: 'Password',
      passwordPlaceholder: '••••••••',
      submit: 'Sign in',
      or: 'or',
      google: 'Continue with Google',
      noAccount: "Don't have an Alias?",
      createOne: 'Create one',
    },
    signUp: {
      title: 'Create an Alias',
      subtitle: 'No real name, ever — just an email and a username only you choose.',
      email: 'Email',
      emailPlaceholder: 'you@example.com',
      password: 'Password',
      passwordPlaceholder: 'At least 8 characters',
      submit: 'Create Alias',
      or: 'or',
      google: 'Continue with Google',
      haveAccount: 'Already have an Alias?',
      signInInstead: 'Sign in',
      checkEmailTitle: 'Check your email',
      checkEmailBody: "We've sent a confirmation link. Tap it, then come back and sign in.",
      backToSignIn: 'Back to sign in',
    },
    username: {
      title: 'Choose a username',
      subtitle: "This is how you'll appear everywhere in Houna — never your real name.",
      placeholder: 'username',
      checking: 'Checking availability…',
      available: 'Available',
      taken: 'Already taken',
      label: 'Username',
      invalid: '3–20 characters — letters, numbers, and underscore only',
      submit: 'Continue',
      changeTitle: 'Change username',
      changeSubtitle: "Your new name shows everywhere you appear in Houna, including Voices and the leaderboard. Your old one becomes free for someone else.",
      same: 'This is your username now',
      limitTwo: 'You can change your username twice every 30 days.',
      limitOne: 'You can change it once more in these 30 days.',
      limitNone: "You've changed it twice in 30 days. You can change it again on {date}.",
      save: 'Save',
    },
    profile: {
      title: 'Your Alias',
      username: 'Username',
      avatar: 'Avatar',
      changePhoto: 'Change photo',
      notSet: 'Not set',
      details: 'Details',
      activity: 'Activity',
      country: 'Country',
      selectCountry: 'Select your country',
      gccGroup: 'Gulf Countries',
      allCountries: 'All countries',
      streakStats: 'Streak & leaderboard',
      signOut: 'Sign out',
      signOutConfirmTitle: 'Sign out?',
      signOutConfirmBody: "You'll need your email and password (or Google) to sign back in.",
      cancel: 'Cancel',
      deleteLink: 'Delete my Alias',
    },
    // Deleting an Alias (app/account/delete.tsx; the App Store requires it).
    deleteAlias: {
      title: 'Delete your Alias',
      subtitle: "This can't be undone. Straight away, Houna deletes:",
      items: [
        'Your Alias name, photo and country',
        'Your practice history, streak, badges and place on the leaderboard',
        'Your test results (My results)',
        'Your Voices posts and their photos',
        "This Alias's notification sign-ups",
      ],
      staysTitle: 'Stays on this phone',
      staysBody: 'Your journal, your mood check-ins and the practice shown in Recap. They were never part of your Alias, and they stay after you delete it.',
      prompt: 'To confirm, type your Alias name:',
      field: 'Alias name',
      button: 'Delete forever',
      cancel: 'Cancel',
      failed: "Your Alias couldn't be deleted. Check your connection and try again.",
    },
    stats: {
      title: 'Your practice',
      subtitle: 'Your breathing and meditation. Mood check-ins never count — they are just for you.',
      // The week as an arc (canvas "Phase 4 — Stats: the week as an arc"), from the phone's own log.
      week: {
        eyebrow: 'This week',
        unit: { one: 'minute', few: 'minutes' },
        lastWeek: 'Last week',
        a11y: 'This week: {n}. Last week: {m}.',
      },
      currentStreak: 'Current streak',
      longestStreak: 'Longest',
      days: {
        one: '{n} day',
        two: '{n} days',
        few: '{n} days',
        many: '{n} days',
      },
      noStreakYet: 'Try a breathing or meditation session to start one.',
      // The week in moons (canvas "Phase 6 — Stats: the week in moons").
      inARow: { one: 'day in a row', few: 'days in a row' },
      moonsLine: 'This week’s moons. Each one lit is a day you practised.',
      moonsA11y: '{n}. This week: {days}.',
      practised: 'practised',
      rest: 'a rest',
      weekdays: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
      weekdayNames: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
      badgesTitle: 'Badges',
      badgeName: {
        one: '{n} day',
        two: '{n} days',
        few: '{n} days',
        many: '{n} days',
      },
      leaderboardTitle: 'Leaderboard',
      leaderboardSubtitle: 'Anonymous and username-only — no one sees more than that.',
      thisWeek: 'This week',
      allTime: 'All time',
      leaderboardEmpty: 'No activity yet this period.',
      you: 'You',
      share: 'Share',
      shareMessage: {
        one: "I'm on a {n}-day streak on Houna 🌿",
        two: "I'm on a {n}-day streak on Houna 🌿",
        few: "I'm on a {n}-day streak on Houna 🌿",
        many: "I'm on a {n}-day streak on Houna 🌿",
      },
    },
    notifications: {
      title: 'Notifications',
      subtitle: 'Choose what Houna can remind you about.',
      reminderTitle: 'Daily reminder',
      onDevice: 'On this device',
      reminderBody: 'A gentle nudge once a day to take a moment for yourself.',
      reminderNotificationTitle: 'Take a moment for yourself',
      reminderNotificationBody: 'A few minutes of breathing or meditation can help.',
      permissionDenied: "Notifications are off in your device settings — Houna can't schedule this until you allow them.",
      remoteHeading: 'For your Alias',
      storyHighlightsTitle: 'Story highlights',
      storyHighlightsBody: "Get notified when a new Story of the Week is featured.",
      communityStatsTitle: 'Community stats',
      communityStatsBody: 'Occasional updates on community milestones.',
      guestNote: 'Sign in with your Alias to also get story and community highlights.',
      signIn: 'Sign in',
    },
    errors: {
      email_in_use: "We couldn't create an Alias with that email. If you already have one, try signing in.",
      weak_password: 'Password must be at least 8 characters.',
      invalid_email: "That doesn't look like a valid email address.",
      invalid_credentials: 'Incorrect email or password.',
      username_taken: 'That username is already taken.',
      invalid_username: '3–20 characters — letters, numbers, and underscore only.',
      username_change_limit: "You've changed your username twice in the last 30 days.",
      cancelled: '',
      unknown: 'Something went wrong — please try again.',
    },
  },
  ar: {
    eyebrow: 'الحساب',
    more: {
      heading: 'الحساب',
      guestTitle: 'أنت تتصفح كزائر',
      guestBody: 'كل ما تفعله لا يُخزَّن إلا على هذا الجهاز. أنشئ اسمًا مستعارًا لحفظ يومياتك في السحابة، والانضمام لخريطة المجتمع، والمزيد.',
      signIn: 'تسجيل الدخول',
      createAlias: 'إنشاء اسم مستعار',
      manageProfile: 'إدارة الملف الشخصي',
      signOut: 'تسجيل الخروج',
      finishSetupTitle: 'أكمل إعداد اسمك المستعار',
      finishSetupBody: 'اختر اسم مستخدم لتبدأ استخدام اسمك المستعار.',
    },
    signIn: {
      title: 'أهلاً بعودتك',
      subtitle: 'سجّل الدخول باسمك المستعار لتكمل من حيث توقفت.',
      email: 'البريد الإلكتروني',
      emailPlaceholder: 'you@example.com',
      password: 'كلمة المرور',
      passwordPlaceholder: '••••••••',
      submit: 'تسجيل الدخول',
      or: 'أو',
      google: 'المتابعة عبر جوجل',
      noAccount: 'ليس لديك اسم مستعار؟',
      createOne: 'أنشئ واحدًا',
    },
    signUp: {
      title: 'إنشاء اسم مستعار',
      subtitle: 'بلا اسم حقيقي أبدًا — فقط بريد إلكتروني واسم مستخدم تختاره بنفسك.',
      email: 'البريد الإلكتروني',
      emailPlaceholder: 'you@example.com',
      password: 'كلمة المرور',
      passwordPlaceholder: '8 أحرف على الأقل',
      submit: 'إنشاء الاسم المستعار',
      or: 'أو',
      google: 'المتابعة عبر جوجل',
      haveAccount: 'لديك اسم مستعار بالفعل؟',
      signInInstead: 'تسجيل الدخول',
      checkEmailTitle: 'تحقق من بريدك الإلكتروني',
      checkEmailBody: 'أرسلنا رابط تأكيد. اضغط عليه ثم عد وسجّل الدخول.',
      backToSignIn: 'العودة لتسجيل الدخول',
    },
    username: {
      title: 'اختر اسم مستخدم',
      subtitle: 'هكذا ستظهر في كل مكان في هُنا — وليس باسمك الحقيقي أبدًا.',
      placeholder: 'اسم المستخدم',
      checking: 'جاري التحقق من التوفر…',
      available: 'متوفر',
      taken: 'مُستخدم بالفعل',
      label: 'اسم المستخدم',
      invalid: '٣–٢٠ حرفًا — أحرف إنجليزية وأرقام وشرطة سفلية فقط',
      submit: 'متابعة',
      changeTitle: 'تغيير اسم المستخدم',
      changeSubtitle: 'سيظهر اسمك الجديد في كل مكان تظهر فيه في هُنا، ومنه «أصوات» وقائمة المتصدرين. ويصبح اسمك القديم متاحًا لغيرك.',
      same: 'هذا اسم المستخدم الحالي',
      limitTwo: 'يمكنك تغيير اسم المستخدم مرتين كل ٣٠ يومًا.',
      limitOne: 'يمكنك تغييره مرة أخرى واحدة خلال هذه الأيام الثلاثين.',
      limitNone: 'غيّرته مرتين خلال ٣٠ يومًا. يمكنك تغييره مجددًا في {date}.',
      save: 'حفظ',
    },
    profile: {
      title: 'اسمك المستعار',
      username: 'اسم المستخدم',
      avatar: 'الصورة الرمزية',
      changePhoto: 'تغيير الصورة',
      notSet: 'غير محدد',
      details: 'التفاصيل',
      activity: 'النشاط',
      country: 'الدولة',
      selectCountry: 'اختر دولتك',
      gccGroup: 'دول الخليج',
      allCountries: 'كل الدول',
      streakStats: 'السلسلة والمتصدرون',
      signOut: 'تسجيل الخروج',
      signOutConfirmTitle: 'تسجيل الخروج؟',
      signOutConfirmBody: 'ستحتاج بريدك الإلكتروني وكلمة المرور (أو جوجل) لتسجيل الدخول مرة أخرى.',
      cancel: 'إلغاء',
      deleteLink: 'حذف اسمي المستعار',
    },
    deleteAlias: {
      title: 'حذف اسمك المستعار',
      subtitle: 'لا يمكن التراجع عن هذا. يحذف هُنا فورًا:',
      items: [
        'اسمك المستعار وصورتك ودولتك',
        'سجلّ ممارستك وسلسلتك وشاراتك ومكانك في قائمة المتصدرين',
        'نتائج اختباراتك (نتائجي)',
        'منشوراتك في «أصوات» وصورها',
        'اشتراكات الإشعارات لهذا الاسم المستعار',
      ],
      staysTitle: 'يبقى على هذا الهاتف',
      staysBody: 'يومياتك، وتسجيلات مزاجك، والممارسة التي يعرضها الملخّص. لم تكن يومًا جزءًا من اسمك المستعار، وتبقى بعد حذفه.',
      prompt: 'للتأكيد، اكتب اسمك المستعار:',
      field: 'الاسم المستعار',
      button: 'حذف نهائي',
      cancel: 'إلغاء',
      failed: 'تعذّر حذف اسمك المستعار. تحقّق من اتصالك وحاول مرة أخرى.',
    },
    stats: {
      title: 'ممارستك',
      subtitle: 'تنفّسك وتأمّلك. تسجيل المزاج لا يُحتسب أبدًا — فهو لك وحدك.',
      week: {
        eyebrow: 'هذا الأسبوع',
        unit: { one: 'دقيقة', two: 'دقيقتان', few: 'دقائق', many: 'دقيقة' },
        lastWeek: 'الأسبوع الماضي',
        a11y: 'هذا الأسبوع: {n}. الأسبوع الماضي: {m}.',
      },
      currentStreak: 'السلسلة الحالية',
      longestStreak: 'الأطول',
      days: {
        one: 'يوم واحد',
        two: 'يومان',
        few: '{n} أيام',
        many: '{n} يومًا',
      },
      noStreakYet: 'جرّب جلسة تنفس أو تأمل لتبدأ سلسلتك.',
      inARow: { one: 'يوم متتالٍ', two: 'يومان متتاليان', few: 'أيام متتالية', many: 'يومًا متتاليًا' },
      moonsLine: 'أقمار هذا الأسبوع. كل قمر مضيء يوم ممارسة.',
      moonsA11y: '{n}. هذا الأسبوع: {days}.',
      practised: 'يوم ممارسة',
      rest: 'راحة',
      weekdays: ['ن', 'ث', 'ر', 'خ', 'ج', 'س', 'ح'],
      weekdayNames: ['الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت', 'الأحد'],
      badgesTitle: 'الشارات',
      badgeName: {
        one: 'يوم واحد',
        two: 'يومان',
        few: '{n} أيام',
        many: '{n} يومًا',
      },
      leaderboardTitle: 'المتصدرون',
      leaderboardSubtitle: 'مجهول وباسم المستخدم فقط — لا أحد يرى أكثر من ذلك.',
      thisWeek: 'هذا الأسبوع',
      allTime: 'كل الأوقات',
      leaderboardEmpty: 'لا يوجد نشاط بعد لهذه الفترة.',
      you: 'أنت',
      share: 'مشاركة',
      shareMessage: {
        one: 'أنا في سلسلة يوم واحد على هُنا 🌿',
        two: 'أنا في سلسلة يومين على هُنا 🌿',
        few: 'أنا في سلسلة {n} أيام على هُنا 🌿',
        many: 'أنا في سلسلة {n} يومًا على هُنا 🌿',
      },
    },
    notifications: {
      title: 'الإشعارات',
      subtitle: 'اختر بما يمكن لهُنا تذكيرك.',
      reminderTitle: 'تذكير يومي',
      onDevice: 'على هذا الجهاز',
      reminderBody: 'تذكير لطيف مرة يوميًا لأخذ لحظة لنفسك.',
      reminderNotificationTitle: 'خذ لحظة لنفسك',
      reminderNotificationBody: 'بضع دقائق من التنفس أو التأمل قد تساعدك.',
      permissionDenied: 'الإشعارات مغلقة في إعدادات جهازك — لا يمكن لهُنا جدولة هذا حتى تسمح بها.',
      remoteHeading: 'لاسمك المستعار',
      storyHighlightsTitle: 'قصص مميزة',
      storyHighlightsBody: 'احصل على إشعار عند نشر قصة أسبوعية جديدة.',
      communityStatsTitle: 'إحصائيات المجتمع',
      communityStatsBody: 'تحديثات بين حين وآخر عن إنجازات المجتمع.',
      guestNote: 'سجّل الدخول باسمك المستعار للحصول أيضًا على القصص المميزة وتحديثات المجتمع.',
      signIn: 'تسجيل الدخول',
    },
    errors: {
      email_in_use: 'تعذّر إنشاء اسم مستعار بهذا البريد الإلكتروني. إن كان لديك واحد بالفعل، جرّب تسجيل الدخول.',
      weak_password: 'يجب ألا تقل كلمة المرور عن 8 أحرف.',
      invalid_email: 'هذا لا يبدو بريدًا إلكترونيًا صالحًا.',
      invalid_credentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
      username_taken: 'اسم المستخدم هذا مُستخدم بالفعل.',
      invalid_username: '٣–٢٠ حرفًا — أحرف إنجليزية وأرقام وشرطة سفلية فقط.',
      username_change_limit: 'غيّرت اسم المستخدم مرتين خلال آخر ٣٠ يومًا.',
      cancelled: '',
      unknown: 'حدث خطأ ما — يرجى المحاولة مرة أخرى.',
    },
  },
};
