/**
 * Strings for the Account area (Segment 1 of the accounts roadmap): the
 * More screen's Account section, sign-in/sign-up, username claiming, and
 * profile management. No old-MVP equivalent to port from — this app never
 * had accounts before now, so this copy is new, written to match this
 * catalogue's existing voice.
 */

export const accountStrings = {
  en: {
    eyebrow: 'Account',
    more: {
      heading: 'ACCOUNT',
      guestTitle: "You're browsing as a guest",
      guestBody: 'Nothing you do is stored beyond this device. Create an Alias to save your journal to the cloud, join the community map, and more.',
      signIn: 'Sign In',
      createAlias: 'Create an Alias',
      manageProfile: 'Manage Profile',
      signOut: 'Sign Out',
      finishSetupTitle: 'Finish setting up your Alias',
      finishSetupBody: 'Choose a username to start using your Alias.',
    },
    signIn: {
      title: 'Welcome back',
      subtitle: 'Sign in to your Alias to pick up where you left off.',
      email: 'Email',
      emailPlaceholder: 'you@example.com',
      password: 'Password',
      passwordPlaceholder: '••••••••',
      submit: 'Sign in',
      or: 'or',
      google: 'Continue with Google',
      noAccount: "Don't have an Alias?",
      createOne: 'Create one',
    },
    signUp: {
      title: 'Create an Alias',
      subtitle: 'No real name, ever — just an email and a username only you choose.',
      email: 'Email',
      emailPlaceholder: 'you@example.com',
      password: 'Password',
      passwordPlaceholder: 'At least 6 characters',
      submit: 'Create Alias',
      or: 'or',
      google: 'Continue with Google',
      haveAccount: 'Already have an Alias?',
      signInInstead: 'Sign in',
      checkEmailTitle: 'Check your email',
      checkEmailBody: "We've sent a confirmation link. Tap it, then come back and sign in.",
      backToSignIn: 'Back to sign in',
    },
    username: {
      title: 'Choose a username',
      subtitle: "This is how you'll appear everywhere in Houna — never your real name.",
      placeholder: 'username',
      checking: 'Checking availability…',
      available: 'Available',
      taken: 'Already taken',
      label: 'Username',
      invalid: '3–20 characters — letters, numbers, and underscore only',
      submit: 'Continue',
    },
    profile: {
      title: 'Your Alias',
      username: 'Username',
      avatar: 'Avatar',
      changePhoto: 'Change photo',
      notSet: 'Not set',
      details: 'Details',
      activity: 'Activity',
      country: 'Country',
      selectCountry: 'Select your country',
      gccGroup: 'Gulf Countries',
      allCountries: 'All countries',
      streakStats: 'Streak & leaderboard',
      signOut: 'Sign out',
      signOutConfirmTitle: 'Sign out?',
      signOutConfirmBody: "You'll need your email and password (or Google) to sign back in.",
      cancel: 'Cancel',
    },
    stats: {
      title: 'Your streak',
      subtitle: 'Days with a breathing or meditation session. Mood check-ins never count — they are just for you.',
      currentStreak: 'Current streak',
      longestStreak: 'Longest',
      days: {
        one: '{n} day',
        two: '{n} days',
        few: '{n} days',
        many: '{n} days',
      },
      noStreakYet: 'Try a breathing or meditation session to start one.',
      badgesTitle: 'Badges',
      badgeName: {
        one: '{n} day',
        two: '{n} days',
        few: '{n} days',
        many: '{n} days',
      },
      leaderboardTitle: 'Leaderboard',
      leaderboardSubtitle: 'Anonymous and username-only — no one sees more than that.',
      thisWeek: 'This week',
      allTime: 'All time',
      leaderboardEmpty: 'No activity yet this period.',
      you: 'You',
      share: 'Share',
      shareMessage: {
        one: "I'm on a {n}-day streak on Houna 🌿",
        two: "I'm on a {n}-day streak on Houna 🌿",
        few: "I'm on a {n}-day streak on Houna 🌿",
        many: "I'm on a {n}-day streak on Houna 🌿",
      },
    },
    notifications: {
      title: 'Notifications',
      subtitle: 'Choose what Houna can remind you about.',
      reminderTitle: 'Daily reminder',
      onDevice: 'On this device',
      reminderBody: 'A gentle nudge once a day to take a moment for yourself.',
      reminderNotificationTitle: 'Take a moment for yourself',
      reminderNotificationBody: 'A few minutes of breathing or meditation can help.',
      permissionDenied: "Notifications are off in your device settings — Houna can't schedule this until you allow them.",
      remoteHeading: 'For your Alias',
      storyHighlightsTitle: 'Story highlights',
      storyHighlightsBody: "Get notified when a new Story of the Week is featured.",
      communityStatsTitle: 'Community stats',
      communityStatsBody: 'Occasional updates on community milestones.',
      guestNote: 'Sign in with your Alias to also get story and community highlights.',
      signIn: 'Sign in',
    },
    errors: {
      email_in_use: 'That email already has an Alias — try signing in instead.',
      weak_password: 'Password must be at least 6 characters.',
      invalid_email: "That doesn't look like a valid email address.",
      invalid_credentials: 'Incorrect email or password.',
      username_taken: 'That username is already taken.',
      invalid_username: '3–20 characters — letters, numbers, and underscore only.',
      cancelled: '',
      unknown: 'Something went wrong — please try again.',
    },
  },
  ar: {
    eyebrow: 'الحساب',
    more: {
      heading: 'الحساب',
      guestTitle: 'أنت تتصفح كزائر',
      guestBody: 'كل ما تفعله لا يُخزَّن إلا على هذا الجهاز. أنشئ اسمًا مستعارًا لحفظ يومياتك في السحابة، والانضمام لخريطة المجتمع، والمزيد.',
      signIn: 'تسجيل الدخول',
      createAlias: 'إنشاء اسم مستعار',
      manageProfile: 'إدارة الملف الشخصي',
      signOut: 'تسجيل الخروج',
      finishSetupTitle: 'أكمل إعداد اسمك المستعار',
      finishSetupBody: 'اختر اسم مستخدم لتبدأ استخدام اسمك المستعار.',
    },
    signIn: {
      title: 'أهلاً بعودتك',
      subtitle: 'سجّل الدخول باسمك المستعار لتكمل من حيث توقفت.',
      email: 'البريد الإلكتروني',
      emailPlaceholder: 'you@example.com',
      password: 'كلمة المرور',
      passwordPlaceholder: '••••••••',
      submit: 'تسجيل الدخول',
      or: 'أو',
      google: 'المتابعة عبر جوجل',
      noAccount: 'ليس لديك اسم مستعار؟',
      createOne: 'أنشئ واحدًا',
    },
    signUp: {
      title: 'إنشاء اسم مستعار',
      subtitle: 'بلا اسم حقيقي أبدًا — فقط بريد إلكتروني واسم مستخدم تختاره بنفسك.',
      email: 'البريد الإلكتروني',
      emailPlaceholder: 'you@example.com',
      password: 'كلمة المرور',
      passwordPlaceholder: '6 أحرف على الأقل',
      submit: 'إنشاء الاسم المستعار',
      or: 'أو',
      google: 'المتابعة عبر جوجل',
      haveAccount: 'لديك اسم مستعار بالفعل؟',
      signInInstead: 'تسجيل الدخول',
      checkEmailTitle: 'تحقق من بريدك الإلكتروني',
      checkEmailBody: 'أرسلنا رابط تأكيد. اضغط عليه ثم عد وسجّل الدخول.',
      backToSignIn: 'العودة لتسجيل الدخول',
    },
    username: {
      title: 'اختر اسم مستخدم',
      subtitle: 'هكذا ستظهر في كل مكان في هُنا — وليس باسمك الحقيقي أبدًا.',
      placeholder: 'اسم المستخدم',
      checking: 'جاري التحقق من التوفر…',
      available: 'متوفر',
      taken: 'مُستخدم بالفعل',
      label: 'اسم المستخدم',
      invalid: '٣–٢٠ حرفًا — أحرف إنجليزية وأرقام وشرطة سفلية فقط',
      submit: 'متابعة',
    },
    profile: {
      title: 'اسمك المستعار',
      username: 'اسم المستخدم',
      avatar: 'الصورة الرمزية',
      changePhoto: 'تغيير الصورة',
      notSet: 'غير محدد',
      details: 'التفاصيل',
      activity: 'النشاط',
      country: 'الدولة',
      selectCountry: 'اختر دولتك',
      gccGroup: 'دول الخليج',
      allCountries: 'كل الدول',
      streakStats: 'السلسلة والمتصدرون',
      signOut: 'تسجيل الخروج',
      signOutConfirmTitle: 'تسجيل الخروج؟',
      signOutConfirmBody: 'ستحتاج بريدك الإلكتروني وكلمة المرور (أو جوجل) لتسجيل الدخول مرة أخرى.',
      cancel: 'إلغاء',
    },
    stats: {
      title: 'سلسلتك',
      subtitle: 'الأيام التي مارست فيها جلسة تنفس أو تأمل. تسجيل المزاج لا يُحتسب أبدًا — فهو لك وحدك.',
      currentStreak: 'السلسلة الحالية',
      longestStreak: 'الأطول',
      days: {
        one: 'يوم واحد',
        two: 'يومان',
        few: '{n} أيام',
        many: '{n} يومًا',
      },
      noStreakYet: 'جرّب جلسة تنفس أو تأمل لتبدأ سلسلتك.',
      badgesTitle: 'الشارات',
      badgeName: {
        one: 'يوم واحد',
        two: 'يومان',
        few: '{n} أيام',
        many: '{n} يومًا',
      },
      leaderboardTitle: 'المتصدرون',
      leaderboardSubtitle: 'مجهول وباسم المستخدم فقط — لا أحد يرى أكثر من ذلك.',
      thisWeek: 'هذا الأسبوع',
      allTime: 'كل الأوقات',
      leaderboardEmpty: 'لا يوجد نشاط بعد لهذه الفترة.',
      you: 'أنت',
      share: 'مشاركة',
      shareMessage: {
        one: 'أنا في سلسلة يوم واحد على هُنا 🌿',
        two: 'أنا في سلسلة يومين على هُنا 🌿',
        few: 'أنا في سلسلة {n} أيام على هُنا 🌿',
        many: 'أنا في سلسلة {n} يومًا على هُنا 🌿',
      },
    },
    notifications: {
      title: 'الإشعارات',
      subtitle: 'اختر بما يمكن لهُنا تذكيرك.',
      reminderTitle: 'تذكير يومي',
      onDevice: 'على هذا الجهاز',
      reminderBody: 'تذكير لطيف مرة يوميًا لأخذ لحظة لنفسك.',
      reminderNotificationTitle: 'خذ لحظة لنفسك',
      reminderNotificationBody: 'بضع دقائق من التنفس أو التأمل قد تساعدك.',
      permissionDenied: 'الإشعارات مغلقة في إعدادات جهازك — لا يمكن لهُنا جدولة هذا حتى تسمح بها.',
      remoteHeading: 'لاسمك المستعار',
      storyHighlightsTitle: 'قصص مميزة',
      storyHighlightsBody: 'احصل على إشعار عند نشر قصة أسبوعية جديدة.',
      communityStatsTitle: 'إحصائيات المجتمع',
      communityStatsBody: 'تحديثات بين حين وآخر عن إنجازات المجتمع.',
      guestNote: 'سجّل الدخول باسمك المستعار للحصول أيضًا على القصص المميزة وتحديثات المجتمع.',
      signIn: 'تسجيل الدخول',
    },
    errors: {
      email_in_use: 'هذا البريد الإلكتروني لديه اسم مستعار بالفعل — جرّب تسجيل الدخول بدلاً من ذلك.',
      weak_password: 'يجب ألا تقل كلمة المرور عن 6 أحرف.',
      invalid_email: 'هذا لا يبدو بريدًا إلكترونيًا صالحًا.',
      invalid_credentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
      username_taken: 'اسم المستخدم هذا مُستخدم بالفعل.',
      invalid_username: '٣–٢٠ حرفًا — أحرف إنجليزية وأرقام وشرطة سفلية فقط.',
      cancelled: '',
      unknown: 'حدث خطأ ما — يرجى المحاولة مرة أخرى.',
    },
  },
};
