/**
 * The nine badges (canvas "Houna — Account & badges (phase 6)"): their names, what each asks,
 * the line said as one is earned, and the badges page. Never a badge for mood or journaling.
 * The Arabic keeps to nouns and "we" where it can, so it never picks a gender.
 */
export const badgeStrings = {
  en: {
    names: {
      first_session: 'First breath',
      streak_3: 'First light',
      streak_7: 'Sunrise',
      streak_14: 'The sun',
      streak_30: 'Half moon',
      streak_100: 'Full moon',
      all_breathing: 'Every breath',
      all_scenes: 'Every scene',
      all_skies: 'Every sky',
    },
    how: {
      first_session: 'Your first breathing or meditation session',
      streak_3: '3 days in a row',
      streak_7: '7 days in a row',
      streak_14: '14 days in a row',
      streak_30: '30 days in a row',
      streak_100: '100 days in a row',
      all_breathing: 'All five breathing exercises',
      all_scenes: 'All four meditation scenes',
      all_skies: 'The sunrise, the dusk and the starfield, from Home',
    },
    // Said as the badge is earned (the unlock moment).
    lines: {
      first_session: 'Your first breath with Houna.',
      streak_3: 'Three days in a row. First light on the horizon.',
      streak_7: 'Seven days in a row. The sun is up.',
      streak_14: 'Fourteen days in a row. The sun is high.',
      streak_30: 'Thirty days in a row. Half the moon is lit.',
      streak_100: 'A hundred days in a row. A full moon.',
      all_breathing: 'All five breathing exercises. Each breath has its colour.',
      all_scenes: 'All four scenes: fire, rain, forest and ocean.',
      all_skies: 'The sunrise, the dusk and the starfield.',
    },
    title: 'Badges',
    count: '{n} of {m}',
    stillAhead: 'Still ahead',
    held: 'Held by {n}% of Houna',
    heldShort: 'Held by {n}%',
    earnedOn: '{date}',
    remaining: { one: '1 more day', few: '{n} more days' },
    empty: 'Your first session lights the first.',
    newBadge: 'New badge',
    lovely: 'Lovely',
    next: 'Next',
    locked: '{name}, not yet: {how}',
    earned: '{name}, earned {date}',
  },
  ar: {
    names: {
      first_session: 'النَّفَس الأول',
      streak_3: 'أول الضوء',
      streak_7: 'الشروق',
      streak_14: 'الشمس',
      streak_30: 'نصف القمر',
      streak_100: 'البدر',
      all_breathing: 'كل الأنفاس',
      all_scenes: 'كل المشاهد',
      all_skies: 'السماء',
    },
    how: {
      first_session: 'أول جلسة تنفّس أو تأمّل',
      streak_3: '٣ أيام متتالية',
      streak_7: '٧ أيام متتالية',
      streak_14: '١٤ يومًا متتاليًا',
      streak_30: '٣٠ يومًا متتاليًا',
      streak_100: '١٠٠ يوم متتالية',
      all_breathing: 'تمارين التنفّس الخمسة',
      all_scenes: 'مشاهد التأمّل الأربعة',
      all_skies: 'الشروق والغسق والنجوم، من الرئيسية',
    },
    lines: {
      first_session: 'أول نَفَس مع هُنا.',
      streak_3: 'ثلاثة أيام متتالية. أول الضوء في الأفق.',
      streak_7: 'سبعة أيام متتالية. أشرقت الشمس.',
      streak_14: 'أربعة عشر يومًا متتاليًا. الشمس في كبد السماء.',
      streak_30: 'ثلاثون يومًا متتاليًا. أضاء نصف القمر.',
      streak_100: 'مئة يوم متتالية. البدر.',
      all_breathing: 'تمارين التنفّس الخمسة كلها. لكل نَفَس لونه.',
      all_scenes: 'المشاهد الأربعة: النار والمطر والغابة والبحر.',
      all_skies: 'الشروق والغسق والسماء المرصّعة بالنجوم.',
    },
    title: 'الشارات',
    count: '{n} من {m}',
    stillAhead: 'ما زال أمامك',
    held: 'يحملها {n}٪ من هُنا',
    heldShort: 'يحملها {n}٪',
    earnedOn: '{date}',
    remaining: { one: 'بقي يوم واحد', two: 'بقي يومان', few: 'بقيت {n} أيام', many: 'بقي {n} يومًا' },
    empty: 'أول جلسة تضيء أولاها.',
    newBadge: 'شارة جديدة',
    lovely: 'جميل',
    next: 'التالية',
    locked: '{name}، لم تُنَل بعد: {how}',
    earned: '{name}، نِيلت في {date}',
  },
};

/**
 * My results (the held plan's "My results"): every questionnaire taken, newest first. One tap
 * from Profile, never on the Profile page itself (shared phones).
 */
export const resultsStrings = {
  en: {
    eyebrow: 'Your reflections',
    title: 'My results',
    body: 'Every questionnaire you’ve taken. They stay on this phone unless you save them to your profile.',
    saved: 'Saved to profile',
    traits: { one: '{n} trait', few: '{n} traits' },
    holdToDelete: 'Press and hold a result to delete it.',
    deleteTitle: 'Delete this result?',
    deleteBody: 'It will be removed from this phone.',
    delete: 'Delete',
    cancel: 'Cancel',
    deleteHint: 'Press and hold to delete',
    emptyTitle: 'No results yet',
    emptyBody: 'Short questionnaires in Discover help you understand yourself a little better.',
    emptyAction: 'Go to Discover',
  },
  ar: {
    eyebrow: 'تأمّلاتك',
    title: 'نتائجي',
    body: 'كل استبيان أجبته. تبقى على هذا الهاتف ما لم تحفظها في ملفك.',
    saved: 'محفوظة في ملفك',
    traits: { one: 'سمة واحدة', two: 'سمتان', few: '{n} سمات', many: '{n} سمة' },
    holdToDelete: 'اضغط مطوّلًا على نتيجة لحذفها.',
    deleteTitle: 'حذف هذه النتيجة؟',
    deleteBody: 'ستُحذف من هذا الهاتف.',
    delete: 'حذف',
    cancel: 'إلغاء',
    deleteHint: 'اضغط مطوّلًا للحذف',
    emptyTitle: 'لا نتائج بعد',
    emptyBody: 'استبيانات قصيرة في «اكتشف» تساعد على فهم النفس أكثر قليلًا.',
    emptyAction: 'اذهب إلى «اكتشف»',
  },
};
