/**
 * Strings for the Directory tab (hub + professionals/organizations/wellness
 * centers list & detail screens). Split out of constants/strings.ts for
 * size, same as tanafasStrings.ts.
 *
 * The old MVP's directory screens ported real *data* through the API's own
 * `lang` param, but never translated their own UI chrome (labels, filters,
 * empty/error states) into Arabic — that's all translated fresh here.
 * Only DirectoryScreen.tsx (the hub) had real ported Arabic.
 */

export const directoryStrings = {
  en: {
    /** Unified directory search (canvas "Directory search"). */
    search: {
      eyebrow: 'Directory',
      title: 'What are you looking for?',
      placeholder: 'Topics, articles, professionals, podcasts',
      inputLabel: 'Search the directory',
      clear: 'Clear search',
      filtersLabel: 'Result type',
      filters: {
        all: 'All',
        topics: 'Topics',
        articles: 'Articles',
        professionals: 'Professionals',
        podcasts: 'Podcasts',
      },
      sections: {
        topic: 'Topic',
        articles: 'Articles',
        professionals: 'Professionals',
        professionalsNear: 'Professionals near you · {country}',
        podcasts: 'Podcasts',
        places: 'Organizations & wellness centers',
      },
      seeAll: 'See all',
      showLess: 'Show less',
      learnMore: 'Learn more',
      articleMeta: 'Article · {source}',
      podcastMeta: 'Podcast · {source}',
      orgCount: { one: '{n} organization', few: '{n} organizations' },
      wellnessCount: { one: '{n} wellness center', few: '{n} wellness centers' },
      matching: 'matching “{q}”',
      noResults: 'Nothing matched “{q}”.',
      noResultsHint: 'Try another word, or browse the directory below.',
      loading: 'Searching…',
      partialError: "Some results couldn't load.",
      crisis: "If you're struggling right now, talk to someone today.",
      browse: 'Browse',
    },
    hub: {
      title: 'Directory',
      subtitle: 'Find the right support for your mental health journey.',
      professionalsTitle: 'Mental Health Professionals',
      professionalsSubtitle: 'Therapists, psychiatrists, and doctors ready to help',
      organizationsTitle: 'Organizations',
      organizationsSubtitle: 'Mental health organizations across the region',
      wellnessTitle: 'Wellness Centers',
      wellnessSubtitle: 'Find wellness centers and their services',
      articlesTitle: 'Articles',
      articlesSubtitle: 'Reading on mental health topics, from houna.org',
      podcastsTitle: 'Podcasts',
      podcastsSubtitle: 'Episodes and shows, from houna.org',
      resourcesTitle: 'Mental Health Directory',
      resourcesSubtitle: 'Browse topics — anxiety, depression, and more',
    },
    common: {
      all: 'All',
      filters: 'Filters',
      filterByCountry: 'Filter by country',
      country: 'Country',
      resetFilters: 'Reset filters',
      resetFilter: 'Reset filter',
      tryAgain: 'Try again',
      goBack: 'Go back',
      profile: 'Profile',
      follow: 'Follow',
      visitWebsite: 'Visit website',
      call: 'Call',
      sendEmail: 'Send Email',
      contact: 'Contact',
      notFound: 'Not found',
      about: 'About',
      services: 'Services',
      partOf: 'Part of',
      website: 'Website',
      findProfessional: 'Find a professional',
      facts: {
        location: 'Location',
        languages: 'Languages',
        organizations: 'Organization',
        workWith: 'Works with',
        experience: 'Experience',
        countries: 'Countries',
      },
      reachedEnd: "You've reached the end",
      loadMore: 'Load more',
      noResults: 'No results found',
      moreCount: (n: string) => `+${n} more`,
    },
    professionals: {
      title: 'Professionals',
      loading: 'Loading professionals...',
      error: 'Failed to load professionals',
      loadingProfile: 'Loading profile...',
      errorProfile: 'Failed to load profile',
      count: { one: '{n} professional', few: '{n} professionals' },
      lookingFor: 'Looking For',
      profession: 'Profession',
      sortBy: 'Sort by',
      specialties: 'Specialties',
      availability: [
        { value: '', label: 'All' },
        { value: 'offline', label: 'Offline Sessions' },
        { value: 'online', label: 'Online Sessions' },
      ],
      professionOptions: [
        { value: '', label: 'All' },
        { value: '1', label: 'Doctor' },
        { value: '2', label: 'Therapist' },
        { value: '3', label: 'Psychiatrist' },
      ],
      sortOptions: [
        { value: 'name-ASC', label: 'Alphabetical, A to Z' },
        { value: 'name-DESC', label: 'Alphabetical, Z to A' },
        { value: 'created_at-ASC', label: 'Date, old to new' },
        { value: 'created_at-DESC', label: 'Date, new to old' },
      ],
    },
    organizations: {
      title: 'Organizations',
      loading: 'Loading organizations...',
      error: 'Failed to load organizations',
      loadingDetail: 'Loading organization...',
      errorDetail: 'Failed to load organization',
      count: { one: '{n} organization', few: '{n} organizations' },
      roster: 'Mental Health Professionals',
    },
    wellnessCenters: {
      title: 'Wellness Centers',
      badge: 'Wellness Center',
      loading: 'Loading wellness centers...',
      error: 'Failed to load wellness centers',
      loadingDetail: 'Loading wellness center...',
      errorDetail: 'Failed to load wellness center',
      count: { one: '{n} wellness center', few: '{n} wellness centers' },
    },
    articles: {
      title: 'Articles',
      loading: 'Loading articles...',
      error: 'Failed to load articles',
      count: { one: '{n} article', few: '{n} articles' },
    },
    podcasts: {
      title: 'Podcasts',
      loading: 'Loading podcasts...',
      error: 'Failed to load podcasts',
      count: { one: '{n} podcast', few: '{n} podcasts' },
    },
    resources: {
      loading: 'Loading directory...',
      error: 'Failed to load directory',
      learnMore: 'Learn more',
      intro: 'Clear, gentle guides to common mental health topics: what they are, what helps, and where to find support.',
      topicCount: { one: '{n} topic', few: '{n} topics' },
      detailLoading: 'Loading topic...',
      detailError: 'Failed to load topic',
      noContent: 'No content available for this topic.',
      topicEyebrow: 'Mental health topic',
      sectionsLabel: 'Sections',
    },
  },
  ar: {
    search: {
      eyebrow: 'الدليل',
      title: 'عمّ تبحث؟',
      placeholder: 'مواضيع، مقالات، مختصون، بودكاست',
      inputLabel: 'ابحث في الدليل',
      clear: 'مسح البحث',
      filtersLabel: 'نوع النتيجة',
      filters: {
        all: 'الكل',
        topics: 'المواضيع',
        articles: 'المقالات',
        professionals: 'المختصون',
        podcasts: 'البودكاست',
      },
      sections: {
        topic: 'موضوع',
        articles: 'مقالات',
        professionals: 'المختصون',
        professionalsNear: 'مختصون بالقرب منك · {country}',
        podcasts: 'البودكاست',
        places: 'المنظمات ومراكز العافية',
      },
      seeAll: 'عرض الكل',
      showLess: 'عرض أقل',
      learnMore: 'اعرف المزيد',
      articleMeta: 'مقال · {source}',
      podcastMeta: 'بودكاست · {source}',
      orgCount: { one: 'منظمة واحدة', two: 'منظمتان', few: '{n} منظمات', many: '{n} منظمة' },
      wellnessCount: { one: 'مركز عافية واحد', two: 'مركزا عافية', few: '{n} مراكز عافية', many: '{n} مركز عافية' },
      matching: 'تطابق «{q}»',
      noResults: 'لا توجد نتائج لـ«{q}».',
      noResultsHint: 'جرّب كلمة أخرى، أو تصفّح الدليل أدناه.',
      loading: 'جارٍ البحث…',
      partialError: 'تعذّر تحميل بعض النتائج.',
      crisis: 'إن كنت تمرّ بوقت صعب الآن، تحدّث إلى أحدٍ اليوم.',
      browse: 'تصفّح',
    },
    hub: {
      title: 'الدليل',
      subtitle: 'اعثر على الدعم المناسب لرحلتك في الصحة النفسية.',
      professionalsTitle: 'المختصون في الصحة النفسية',
      professionalsSubtitle: 'معالجون وأطباء نفسيون مستعدون للمساعدة',
      organizationsTitle: 'المنظمات',
      organizationsSubtitle: 'منظمات الصحة النفسية في المنطقة',
      wellnessTitle: 'مراكز العافية',
      wellnessSubtitle: 'اعثر على مراكز العافية وخدماتها',
      articlesTitle: 'المقالات',
      articlesSubtitle: 'قراءات في مواضيع الصحة النفسية، من موقع هُنا',
      podcastsTitle: 'البودكاست',
      podcastsSubtitle: 'حلقات وبرامج، من موقع هُنا',
      resourcesTitle: 'دليل الصحة النفسية',
      resourcesSubtitle: 'تصفّح المواضيع — القلق والاكتئاب والمزيد',
    },
    common: {
      all: 'الكل',
      filters: 'الفلاتر',
      filterByCountry: 'تصفية حسب الدولة',
      country: 'الدولة',
      resetFilters: 'إعادة تعيين الفلاتر',
      resetFilter: 'إعادة تعيين الفلتر',
      tryAgain: 'حاول مرة أخرى',
      goBack: 'رجوع',
      profile: 'الملف الشخصي',
      follow: 'تابعنا',
      visitWebsite: 'زيارة الموقع',
      call: 'اتصال',
      sendEmail: 'إرسال بريد إلكتروني',
      contact: 'تواصل',
      notFound: 'غير موجود',
      about: 'نبذة',
      services: 'الخدمات',
      partOf: 'جزء من',
      website: 'الموقع الإلكتروني',
      findProfessional: 'ابحث عن مختص',
      facts: {
        location: 'الموقع',
        languages: 'اللغات',
        organizations: 'المنظمة',
        workWith: 'يعمل مع',
        experience: 'الخبرة',
        countries: 'الدول',
      },
      reachedEnd: 'لقد وصلت إلى النهاية',
      loadMore: 'تحميل المزيد',
      noResults: 'لا توجد نتائج',
      moreCount: (n: string) => `+${n} أخرى`,
    },
    professionals: {
      title: 'المختصون',
      loading: 'جاري تحميل المختصين...',
      error: 'فشل تحميل المختصين',
      loadingProfile: 'جاري تحميل الملف الشخصي...',
      errorProfile: 'فشل تحميل الملف الشخصي',
      count: { one: 'مختص واحد', two: 'مختصان', few: '{n} مختصين', many: '{n} مختصًا' },
      lookingFor: 'تبحث عن',
      profession: 'المهنة',
      sortBy: 'الترتيب حسب',
      specialties: 'التخصصات',
      availability: [
        { value: '', label: 'الكل' },
        { value: 'offline', label: 'جلسات حضورية' },
        { value: 'online', label: 'جلسات عبر الإنترنت' },
      ],
      professionOptions: [
        { value: '', label: 'الكل' },
        { value: '1', label: 'طبيب' },
        { value: '2', label: 'معالج' },
        { value: '3', label: 'طبيب نفسي' },
      ],
      sortOptions: [
        { value: 'name-ASC', label: 'أبجدياً، أ إلى ي' },
        { value: 'name-DESC', label: 'أبجدياً، ي إلى أ' },
        { value: 'created_at-ASC', label: 'التاريخ، الأقدم أولاً' },
        { value: 'created_at-DESC', label: 'التاريخ، الأحدث أولاً' },
      ],
    },
    organizations: {
      title: 'المنظمات',
      loading: 'جاري تحميل المنظمات...',
      error: 'فشل تحميل المنظمات',
      loadingDetail: 'جاري تحميل المنظمة...',
      errorDetail: 'فشل تحميل المنظمة',
      count: { one: 'منظمة واحدة', two: 'منظمتان', few: '{n} منظمات', many: '{n} منظمة' },
      roster: 'المختصون في الصحة النفسية',
    },
    wellnessCenters: {
      title: 'مراكز العافية',
      badge: 'مركز عافية',
      loading: 'جاري تحميل مراكز العافية...',
      error: 'فشل تحميل مراكز العافية',
      loadingDetail: 'جاري تحميل مركز العافية...',
      errorDetail: 'فشل تحميل مركز العافية',
      count: { one: 'مركز عافية واحد', two: 'مركزا عافية', few: '{n} مراكز عافية', many: '{n} مركز عافية' },
    },
    articles: {
      title: 'المقالات',
      loading: 'جاري تحميل المقالات...',
      error: 'فشل تحميل المقالات',
      count: { one: 'مقالة واحدة', two: 'مقالتان', few: '{n} مقالات', many: '{n} مقالة' },
    },
    podcasts: {
      title: 'البودكاست',
      loading: 'جاري تحميل حلقات البودكاست...',
      error: 'فشل تحميل حلقات البودكاست',
      count: { one: 'حلقة واحدة', two: 'حلقتان', few: '{n} حلقات', many: '{n} حلقة' },
    },
    resources: {
      loading: 'جاري تحميل الدليل...',
      error: 'فشل تحميل الدليل',
      learnMore: 'اعرف المزيد',
      intro: 'أدلة واضحة ولطيفة لمواضيع الصحة النفسية الشائعة: ما هي، وما الذي يساعد، وأين تجد الدعم.',
      topicCount: { one: 'موضوع واحد', two: 'موضوعان', few: '{n} مواضيع', many: '{n} موضوعًا' },
      detailLoading: 'جاري تحميل الموضوع...',
      detailError: 'فشل تحميل الموضوع',
      noContent: 'لا يوجد محتوى متاح لهذا الموضوع.',
      topicEyebrow: 'موضوع في الصحة النفسية',
      sectionsLabel: 'الأقسام',
    },
  },
} as const;
