/**
 * Strings for the Directory tab (hub + professionals/organizations/wellness
 * centers list & detail screens). Split out of constants/strings.ts for
 * size, same as tanafasStrings.ts.
 *
 * The old MVP's directory screens ported real *data* through the API's own
 * `lang` param, but never translated their own UI chrome (labels, filters,
 * empty/error states) into Arabic — that's all translated fresh here.
 * Only DirectoryScreen.tsx (the hub) had real ported Arabic.
 */

export const directoryStrings = {
  en: {
    hub: {
      title: 'Directory',
      subtitle: 'Find the right support for your mental health journey.',
      professionalsTitle: 'Mental Health Professionals',
      professionalsSubtitle: 'Therapists, psychiatrists, and doctors ready to help',
      organizationsTitle: 'Organizations',
      organizationsSubtitle: 'Mental health organizations across the region',
      wellnessTitle: 'Wellness Centers',
      wellnessSubtitle: 'Find wellness centers and their services',
      articlesTitle: 'Articles',
      articlesSubtitle: 'Reading on mental health topics, from houna.org',
      podcastsTitle: 'Podcasts',
      podcastsSubtitle: 'Episodes and shows, from houna.org',
      resourcesTitle: 'Mental Health Directory',
      resourcesSubtitle: 'Browse topics — anxiety, depression, and more',
    },
    common: {
      all: 'All',
      filters: 'Filters',
      filterByCountry: 'Filter by country',
      country: 'Country',
      resetFilters: 'Reset filters',
      resetFilter: 'Reset filter',
      tryAgain: 'Try again',
      goBack: 'Go back',
      profile: 'Profile',
      follow: 'Follow',
      visitWebsite: 'Visit website',
      call: 'Call',
      sendEmail: 'Send Email',
      contact: 'Contact',
      notFound: 'Not found',
      reachedEnd: "You've reached the end",
      loadMore: 'Load more',
      noResults: 'No results found',
      moreCount: (n: string) => `+${n} more`,
    },
    professionals: {
      title: 'Professionals',
      loading: 'Loading professionals...',
      error: 'Failed to load professionals',
      loadingProfile: 'Loading profile...',
      errorProfile: 'Failed to load profile',
      countOne: 'professional',
      countOther: 'professionals',
      lookingFor: 'Looking For',
      profession: 'Profession',
      sortBy: 'Sort by',
      specialties: 'Specialties',
      availability: [
        { value: '', label: 'All' },
        { value: 'offline', label: 'Offline Sessions' },
        { value: 'online', label: 'Online Sessions' },
      ],
      professionOptions: [
        { value: '', label: 'All' },
        { value: '1', label: 'Doctor' },
        { value: '2', label: 'Therapist' },
        { value: '3', label: 'Psychiatrist' },
      ],
      sortOptions: [
        { value: 'name-ASC', label: 'Alphabetical, A to Z' },
        { value: 'name-DESC', label: 'Alphabetical, Z to A' },
        { value: 'created_at-ASC', label: 'Date, old to new' },
        { value: 'created_at-DESC', label: 'Date, new to old' },
      ],
    },
    organizations: {
      title: 'Organizations',
      loading: 'Loading organizations...',
      error: 'Failed to load organizations',
      loadingDetail: 'Loading organization...',
      errorDetail: 'Failed to load organization',
      countOne: 'organization',
      countOther: 'organizations',
      roster: 'Mental Health Professionals',
    },
    wellnessCenters: {
      title: 'Wellness Centers',
      badge: 'Wellness Center',
      loading: 'Loading wellness centers...',
      error: 'Failed to load wellness centers',
      loadingDetail: 'Loading wellness center...',
      errorDetail: 'Failed to load wellness center',
      countOne: 'wellness center',
      countOther: 'wellness centers',
    },
    articles: {
      title: 'Articles',
      loading: 'Loading articles...',
      error: 'Failed to load articles',
      countOne: 'article',
      countOther: 'articles',
    },
    podcasts: {
      title: 'Podcasts',
      loading: 'Loading podcasts...',
      error: 'Failed to load podcasts',
      countOne: 'podcast',
      countOther: 'podcasts',
    },
    resources: {
      loading: 'Loading directory...',
      error: 'Failed to load directory',
      learnMore: 'Learn more',
      importantArticles: 'Important Articles',
      articlesBlurb: 'Read about a variety of mental health topics and learn how to enhance your life and wellness.',
      detailLoading: 'Loading topic...',
      detailError: 'Failed to load topic',
      noContent: 'No content available for this topic.',
    },
  },
  ar: {
    hub: {
      title: 'الدليل',
      subtitle: 'اعثر على الدعم المناسب لرحلتك في الصحة النفسية.',
      professionalsTitle: 'المختصون في الصحة النفسية',
      professionalsSubtitle: 'معالجون وأطباء نفسيون مستعدون للمساعدة',
      organizationsTitle: 'المنظمات',
      organizationsSubtitle: 'منظمات الصحة النفسية في المنطقة',
      wellnessTitle: 'مراكز العافية',
      wellnessSubtitle: 'اعثر على مراكز العافية وخدماتها',
      articlesTitle: 'المقالات',
      articlesSubtitle: 'قراءات في مواضيع الصحة النفسية، من موقع هُنا',
      podcastsTitle: 'البودكاست',
      podcastsSubtitle: 'حلقات وبرامج، من موقع هُنا',
      resourcesTitle: 'دليل الصحة النفسية',
      resourcesSubtitle: 'تصفّح المواضيع — القلق والاكتئاب والمزيد',
    },
    common: {
      all: 'الكل',
      filters: 'الفلاتر',
      filterByCountry: 'تصفية حسب الدولة',
      country: 'الدولة',
      resetFilters: 'إعادة تعيين الفلاتر',
      resetFilter: 'إعادة تعيين الفلتر',
      tryAgain: 'حاول مرة أخرى',
      goBack: 'رجوع',
      profile: 'الملف الشخصي',
      follow: 'تابعنا',
      visitWebsite: 'زيارة الموقع',
      call: 'اتصال',
      sendEmail: 'إرسال بريد إلكتروني',
      contact: 'تواصل',
      notFound: 'غير موجود',
      reachedEnd: 'لقد وصلت إلى النهاية',
      loadMore: 'تحميل المزيد',
      noResults: 'لا توجد نتائج',
      moreCount: (n: string) => `+${n} أخرى`,
    },
    professionals: {
      title: 'المختصون',
      loading: 'جاري تحميل المختصين...',
      error: 'فشل تحميل المختصين',
      loadingProfile: 'جاري تحميل الملف الشخصي...',
      errorProfile: 'فشل تحميل الملف الشخصي',
      countOne: 'مختص',
      countOther: 'مختصون',
      lookingFor: 'تبحث عن',
      profession: 'المهنة',
      sortBy: 'الترتيب حسب',
      specialties: 'التخصصات',
      availability: [
        { value: '', label: 'الكل' },
        { value: 'offline', label: 'جلسات حضورية' },
        { value: 'online', label: 'جلسات عبر الإنترنت' },
      ],
      professionOptions: [
        { value: '', label: 'الكل' },
        { value: '1', label: 'طبيب' },
        { value: '2', label: 'معالج' },
        { value: '3', label: 'طبيب نفسي' },
      ],
      sortOptions: [
        { value: 'name-ASC', label: 'أبجدياً، أ إلى ي' },
        { value: 'name-DESC', label: 'أبجدياً، ي إلى أ' },
        { value: 'created_at-ASC', label: 'التاريخ، الأقدم أولاً' },
        { value: 'created_at-DESC', label: 'التاريخ، الأحدث أولاً' },
      ],
    },
    organizations: {
      title: 'المنظمات',
      loading: 'جاري تحميل المنظمات...',
      error: 'فشل تحميل المنظمات',
      loadingDetail: 'جاري تحميل المنظمة...',
      errorDetail: 'فشل تحميل المنظمة',
      countOne: 'منظمة',
      countOther: 'منظمات',
      roster: 'المختصون في الصحة النفسية',
    },
    wellnessCenters: {
      title: 'مراكز العافية',
      badge: 'مركز عافية',
      loading: 'جاري تحميل مراكز العافية...',
      error: 'فشل تحميل مراكز العافية',
      loadingDetail: 'جاري تحميل مركز العافية...',
      errorDetail: 'فشل تحميل مركز العافية',
      countOne: 'مركز عافية',
      countOther: 'مراكز عافية',
    },
    articles: {
      title: 'المقالات',
      loading: 'جاري تحميل المقالات...',
      error: 'فشل تحميل المقالات',
      countOne: 'مقالة',
      countOther: 'مقالات',
    },
    podcasts: {
      title: 'البودكاست',
      loading: 'جاري تحميل حلقات البودكاست...',
      error: 'فشل تحميل حلقات البودكاست',
      countOne: 'حلقة',
      countOther: 'حلقات',
    },
    resources: {
      loading: 'جاري تحميل الدليل...',
      error: 'فشل تحميل الدليل',
      learnMore: 'اعرف المزيد',
      importantArticles: 'مقالات هامة',
      articlesBlurb: 'اقرأ عن مجموعة من مواضيع الصحة النفسية وتعلّم كيف تعزّز حياتك ورفاهيتك.',
      detailLoading: 'جاري تحميل الموضوع...',
      detailError: 'فشل تحميل الموضوع',
      noContent: 'لا يوجد محتوى متاح لهذا الموضوع.',
    },
  },
} as const;
