/**
 * Strings for the Directory tab (hub + professionals/organizations/wellness
 * centers list & detail screens). Split out of constants/strings.ts for
 * size, same as tanafasStrings.ts.
 *
 * The old MVP's directory screens ported real *data* through the API's own
 * `lang` param, but never translated their own UI chrome (labels, filters,
 * empty/error states) into Arabic — that's all translated fresh here.
 * Only DirectoryScreen.tsx (the hub) had real ported Arabic.
 */

export const directoryStrings = {
  en: {
    /** Unified directory search (canvas "Directory search"). */
    search: {
      eyebrow: 'Directory',
      title: 'What are you looking for?',
      placeholder: 'Topics, people, exercises, events',
      inputLabel: 'Search the directory',
      clear: 'Clear search',
      // Everyday words for what clinical terms name: each searches its meaning (lib/searchConcepts.ts).
      ownWords: 'In your own words',
      ownWordsIntro: 'Not sure what it’s called? Start with how it feels.',
      feelings: [
        { label: 'Lost my spark', query: 'loss of passion' },
        { label: 'Grieving someone', query: 'grief' },
        { label: 'Things from childhood', query: 'childhood issues' },
        { label: 'Violence or abuse', query: 'violence' },
        { label: 'Burnt out', query: 'burnout' },
        { label: 'Overwhelmed', query: 'overwhelmed' },
        { label: 'Low mood', query: 'low mood' },
        { label: 'Numb or detached', query: 'numbness' },
        { label: 'A big life change', query: 'adjustment' },
        { label: 'Can’t sleep', query: 'lack of sleep' },
        { label: 'Emotionally drained', query: 'emotional exhaustion' },
        { label: 'Hormones or health', query: 'hormones' },
      ],
      filtersLabel: 'Result type',
      filters: {
        all: 'All',
        topics: 'Topics',
        articles: 'Articles',
        professionals: 'Professionals',
        podcasts: 'Podcasts',
        events: 'Events',
        places: 'Places',
      },
      sections: {
        topic: 'Topic',
        articles: 'Articles',
        professionals: 'Professionals',
        professionalsNear: 'Professionals near you · {country}',
        podcasts: 'Podcasts',
        places: 'Organizations & wellness centers',
        events: 'Events & speakers',
      },
      // Tanafas in the results: how a scene is named, and the words each kind is also found by.
      meditateTitle: '{name} meditation',
      // Before typing, and when nothing matched.
      tryTopic: 'Try a topic',
      breatheNow: 'Breathe now',
      // A corrected spelling: "{word}" is lit.
      showingFor: 'Showing results for {word}',
      searchInstead: 'Search for {q} instead',
      kindWords: { breathe: 'breathing exercise', meditate: 'meditation' },
      seeAll: 'See all',
      showLess: 'Show less',
      learnMore: 'Learn more',
      articleMeta: 'Article · {source}',
      podcastMeta: 'Podcast · {source}',
      orgCount: { one: '{n} organization', few: '{n} organizations' },
      wellnessCount: { one: '{n} wellness center', few: '{n} wellness centers' },
      matching: 'matching “{q}”',
      noResults: 'Nothing matched “{q}”.',
      noResultsHint: 'Try another word, one of these topics, or browse the directory.',
      loading: 'Searching…',
      partialError: "Some results couldn't load.",
      crisis: "If you're struggling right now, talk to someone today.",
      // Shown first when a search sounds like someone in crisis (lib/crisisIntent.ts).
      // DRAFT: safety-critical copy, as crisisStrings.ts; needs clinical review.
      crisisCard: {
        title: "You don't have to go through this alone",
        body: "If you're thinking about ending your life, hurting yourself, or you aren't safe where you are, please talk to someone now. There are people ready to listen.",
        action: 'Get support now',
      },
      browse: 'Browse',
    },
    hub: {
      title: 'Directory',
      subtitle: 'Find people and places that can support you.',
      professionalsTitle: 'Mental Health Professionals',
      professionalsSubtitle: 'Therapists, psychiatrists and doctors listed on houna.org',
      organizationsTitle: 'Organizations',
      organizationsSubtitle: 'Mental health organizations across the region',
      wellnessTitle: 'Wellness Centers',
      wellnessSubtitle: 'Find wellness centers and their services',
      articlesTitle: 'Articles',
      articlesSubtitle: 'Reading on mental health topics, from houna.org',
      podcastsTitle: 'Podcasts',
      podcastsSubtitle: 'Episodes and shows, from houna.org',
      mediaTitle: 'Read & listen',
      mediaSubtitle: 'Articles and podcasts on mental health',
      resourcesTitle: 'Mental Health Directory',
      resourcesSubtitle: 'Browse topics — anxiety, depression, and more',
    },
    common: {
      all: 'All',
      filters: 'Filters',
      filterByCountry: 'Filter by country',
      country: 'Country',
      resetFilters: 'Reset filters',
      resetFilter: 'Reset filter',
      tryAgain: 'Try again',
      goBack: 'Go back',
      profile: 'Profile',
      follow: 'Follow',
      visitWebsite: 'Visit website',
      call: 'Call',
      sendEmail: 'Send Email',
      contact: 'Contact',
      notFound: 'Not found',
      about: 'About',
      services: 'Services',
      partOf: 'Part of',
      website: 'Website',
      findProfessional: 'Find a professional',
      facts: {
        location: 'Location',
        languages: 'Languages',
        organizations: 'Organization',
        workWith: 'Works with',
        experience: 'Experience',
        countries: 'Countries',
      },
      reachedEnd: "You've reached the end",
      loadMore: 'Load more',
      noResults: 'No results found',
      moreCount: (n: string) => `+${n} more`,
    },
    professionals: {
      title: 'Professionals',
      loading: 'Loading professionals...',
      error: 'Failed to load professionals',
      loadingProfile: 'Loading profile...',
      errorProfile: 'Failed to load profile',
      count: { one: '{n} professional', few: '{n} professionals' },
      specialties: 'Specialties',
      searchPlaceholder: 'Search names or specialties',
      profession: 'Profession',
      worksWith: 'Works with',
      groups: {
        psychologist: 'Psychologists',
        psychiatrist: 'Psychiatrists',
        therapist: 'Therapists & counsellors',
        development: 'Child development',
      },
      groupHints: {
        psychologist: 'Assessment and talking therapy',
        psychiatrist: 'Medical doctors who can prescribe medicine',
        therapist: 'Counselling, coaching and psychotherapy',
        development: 'Speech, behaviour and occupational therapy',
      },
      ages: { children: 'Children', adolescents: 'Teenagers', adults: 'Adults' },
      anyProfession: 'Any profession',
      anyCountry: 'Any country',
      anyone: 'Anyone',
      online: 'Offers online sessions',
      clear: 'Clear',
      noMatch: 'No one matches yet. Try fewer filters or other words.',
    },
    organizations: {
      title: 'Organizations',
      searchPlaceholder: 'Search organizations',
      loading: 'Loading organizations...',
      error: 'Failed to load organizations',
      loadingDetail: 'Loading organization...',
      errorDetail: 'Failed to load organization',
      count: { one: '{n} organization', few: '{n} organizations' },
      roster: 'Mental Health Professionals',
    },
    // Read & listen (components/directory/MediaHub.tsx): articles and podcasts in one place.
    media: {
      title: 'Read & listen',
      intro: 'Articles and podcasts on mental health, gathered by Houna.',
      searchPlaceholder: 'Search articles and podcasts',
      tabs: { all: 'All', articles: 'Articles', podcasts: 'Podcasts' },
      topics: {
        help: 'Getting help',
        anxiety: 'Anxiety & stress',
        mood: 'Low mood & grief',
        children: 'Children & families',
        relationships: 'Relationships',
        trauma: 'Trauma & violence',
        neurodiversity: 'Autism, ADHD & learning',
        addiction: 'Addiction',
        work: 'Work & burnout',
        wellbeing: 'Everyday wellbeing',
      },
      featured: 'Featured',
      listen: 'Listen',
      read: 'Read',
      otherLanguage: 'In Arabic',
      article: 'Article',
      podcast: 'Podcast',
      opensIn: 'Opens in Houna',
      empty: 'Nothing matches yet. Try another word or topic.',
      loading: 'Loading…',
      error: 'Couldn’t load articles and podcasts',
    },
    wellnessCenters: {
      title: 'Wellness Centers',
      searchPlaceholder: 'Search centers or services',
      badge: 'Wellness Center',
      loading: 'Loading wellness centers...',
      error: 'Failed to load wellness centers',
      loadingDetail: 'Loading wellness center...',
      errorDetail: 'Failed to load wellness center',
      count: { one: '{n} wellness center', few: '{n} wellness centers' },
    },
    articles: {
      title: 'Articles',
      loading: 'Loading articles...',
      error: 'Failed to load articles',
      count: { one: '{n} article', few: '{n} articles' },
    },
    podcasts: {
      title: 'Podcasts',
      loading: 'Loading podcasts...',
      error: 'Failed to load podcasts',
      count: { one: '{n} podcast', few: '{n} podcasts' },
    },
    resources: {
      loading: 'Loading directory...',
      error: 'Failed to load directory',
      learnMore: 'Learn more',
      intro: 'Clear, gentle guides to common mental health topics: what they are, what helps, and where to find support.',
      topicCount: { one: '{n} topic', few: '{n} topics' },
      detailLoading: 'Loading topic...',
      detailError: 'Failed to load topic',
      noContent: 'No content available for this topic.',
      topicEyebrow: 'Mental health topic',
      sectionsLabel: 'Sections',
    },
  },
  ar: {
    search: {
      eyebrow: 'الدليل',
      title: 'عمّ تبحث؟',
      placeholder: 'مواضيع، مختصون، تمارين، فعاليات',
      inputLabel: 'ابحث في الدليل',
      clear: 'مسح البحث',
      ownWords: 'بكلماتك أنت',
      ownWordsIntro: 'لا تعرف اسمه؟ ابدأ بما تشعر به.',
      feelings: [
        { label: 'فقدت شغفي', query: 'فقدان الشغف' },
        { label: 'أفتقد شخصًا عزيزًا', query: 'الفقد' },
        { label: 'أمور من الطفولة', query: 'مشاكل الطفولة' },
        { label: 'عنف أو إساءة', query: 'عنف' },
        { label: 'احتراق وظيفي', query: 'احتراق' },
        { label: 'الأمور أكثر مني', query: 'فوق طاقتي' },
        { label: 'مزاج منخفض', query: 'مزاج منخفض' },
        { label: 'خدر أو انفصال عن مشاعري', query: 'تبلد' },
        { label: 'تغيير كبير في حياتي', query: 'التأقلم' },
        { label: 'لا أستطيع النوم', query: 'قلة النوم' },
        { label: 'استنزاف عاطفي', query: 'استنزاف' },
        { label: 'هرمونات أو صحة جسدية', query: 'هرمونات' },
      ],
      filtersLabel: 'نوع النتيجة',
      filters: {
        all: 'الكل',
        topics: 'المواضيع',
        articles: 'المقالات',
        professionals: 'المختصون',
        podcasts: 'البودكاست',
        events: 'الفعاليات',
        places: 'الأماكن',
      },
      sections: {
        topic: 'موضوع',
        articles: 'مقالات',
        professionals: 'المختصون',
        professionalsNear: 'مختصون بالقرب منك · {country}',
        podcasts: 'البودكاست',
        places: 'المنظمات ومراكز العافية',
        events: 'الفعاليات والمتحدثون',
      },
      meditateTitle: 'تأمّل {name}',
      tryTopic: 'جرّب موضوعاً',
      breatheNow: 'تنفّس الآن',
      showingFor: 'نتائج البحث عن {word}',
      searchInstead: 'ابحث عن «{q}» بدلاً من ذلك',
      kindWords: { breathe: 'تمرين تنفس', meditate: 'تأمل' },
      seeAll: 'عرض الكل',
      showLess: 'عرض أقل',
      learnMore: 'اعرف المزيد',
      articleMeta: 'مقال · {source}',
      podcastMeta: 'بودكاست · {source}',
      orgCount: { one: 'منظمة واحدة', two: 'منظمتان', few: '{n} منظمات', many: '{n} منظمة' },
      wellnessCount: { one: 'مركز عافية واحد', two: 'مركزا عافية', few: '{n} مراكز عافية', many: '{n} مركز عافية' },
      matching: 'تطابق «{q}»',
      noResults: 'لا توجد نتائج لـ«{q}».',
      noResultsHint: 'جرّب كلمة أخرى، أو أحد هذه المواضيع، أو تصفّح الدليل.',
      loading: 'جارٍ البحث…',
      partialError: 'تعذّر تحميل بعض النتائج.',
      crisis: 'إن كنت تمرّ بوقت صعب الآن، تحدّث إلى أحدٍ اليوم.',
      // DRAFT: needs review by a native clinical reviewer, as crisisStrings.ts.
      crisisCard: {
        title: 'لست مضطراً لمواجهة هذا وحدك',
        body: 'إذا كنت تفكّر في إنهاء حياتك أو إيذاء نفسك، أو لست في أمان حيث أنت، أرجوك تحدّث إلى أحدٍ الآن. هناك من هو مستعدّ للإصغاء إليك.',
        action: 'احصل على الدعم الآن',
      },
      browse: 'تصفّح',
    },
    hub: {
      title: 'الدليل',
      subtitle: 'اعثر على أشخاص وأماكن يمكنهم دعمك.',
      professionalsTitle: 'المختصون في الصحة النفسية',
      professionalsSubtitle: 'معالجون وأطباء نفسيون مدرجون على houna.org',
      organizationsTitle: 'المنظمات',
      organizationsSubtitle: 'منظمات الصحة النفسية في المنطقة',
      wellnessTitle: 'مراكز العافية',
      wellnessSubtitle: 'اعثر على مراكز العافية وخدماتها',
      articlesTitle: 'المقالات',
      articlesSubtitle: 'قراءات في مواضيع الصحة النفسية، من موقع هُنا',
      podcastsTitle: 'البودكاست',
      podcastsSubtitle: 'حلقات وبرامج، من موقع هُنا',
      mediaTitle: 'اقرأ واستمع',
      mediaSubtitle: 'مقالات وبودكاست عن الصحة النفسية',
      resourcesTitle: 'دليل الصحة النفسية',
      resourcesSubtitle: 'تصفّح المواضيع — القلق والاكتئاب والمزيد',
    },
    common: {
      all: 'الكل',
      filters: 'الفلاتر',
      filterByCountry: 'تصفية حسب الدولة',
      country: 'الدولة',
      resetFilters: 'إعادة تعيين الفلاتر',
      resetFilter: 'إعادة تعيين الفلتر',
      tryAgain: 'حاول مرة أخرى',
      goBack: 'رجوع',
      profile: 'الملف الشخصي',
      follow: 'تابعنا',
      visitWebsite: 'زيارة الموقع',
      call: 'اتصال',
      sendEmail: 'إرسال بريد إلكتروني',
      contact: 'تواصل',
      notFound: 'غير موجود',
      about: 'نبذة',
      services: 'الخدمات',
      partOf: 'جزء من',
      website: 'الموقع الإلكتروني',
      findProfessional: 'ابحث عن مختص',
      facts: {
        location: 'الموقع',
        languages: 'اللغات',
        organizations: 'المنظمة',
        workWith: 'يعمل مع',
        experience: 'الخبرة',
        countries: 'الدول',
      },
      reachedEnd: 'لقد وصلت إلى النهاية',
      loadMore: 'تحميل المزيد',
      noResults: 'لا توجد نتائج',
      moreCount: (n: string) => `+${n} أخرى`,
    },
    professionals: {
      title: 'المختصون',
      loading: 'جاري تحميل المختصين...',
      error: 'فشل تحميل المختصين',
      loadingProfile: 'جاري تحميل الملف الشخصي...',
      errorProfile: 'فشل تحميل الملف الشخصي',
      count: { one: 'مختص واحد', two: 'مختصان', few: '{n} مختصين', many: '{n} مختصًا' },
      specialties: 'التخصصات',
      searchPlaceholder: 'ابحث بالاسم أو التخصص',
      profession: 'التخصص',
      worksWith: 'يعمل مع',
      groups: {
        psychologist: 'أخصائيون نفسيون',
        psychiatrist: 'أطباء نفسيون',
        therapist: 'معالجون ومرشدون',
        development: 'نمو الطفل',
      },
      groupHints: {
        psychologist: 'تقييم وعلاج بالحديث',
        psychiatrist: 'أطباء يمكنهم وصف الأدوية',
        therapist: 'إرشاد وتدريب وعلاج نفسي',
        development: 'نطق وسلوك وعلاج وظيفي',
      },
      ages: { children: 'الأطفال', adolescents: 'المراهقون', adults: 'البالغون' },
      anyProfession: 'أي تخصص',
      anyCountry: 'أي دولة',
      anyone: 'الجميع',
      online: 'يقدّم جلسات عن بُعد',
      clear: 'مسح',
      noMatch: 'لا أحد يطابق بعد. جرّب فلاتر أقل أو كلمات أخرى.',
    },
    organizations: {
      title: 'المنظمات',
      searchPlaceholder: 'ابحث في المنظمات',
      loading: 'جاري تحميل المنظمات...',
      error: 'فشل تحميل المنظمات',
      loadingDetail: 'جاري تحميل المنظمة...',
      errorDetail: 'فشل تحميل المنظمة',
      count: { one: 'منظمة واحدة', two: 'منظمتان', few: '{n} منظمات', many: '{n} منظمة' },
      roster: 'المختصون في الصحة النفسية',
    },
    media: {
      title: 'اقرأ واستمع',
      intro: 'مقالات وبودكاست عن الصحة النفسية، جمعها لك هُنا.',
      searchPlaceholder: 'ابحث في المقالات والبودكاست',
      tabs: { all: 'الكل', articles: 'المقالات', podcasts: 'البودكاست' },
      topics: {
        help: 'طلب المساعدة',
        anxiety: 'القلق والضغط',
        mood: 'المزاج المنخفض والفقد',
        children: 'الأطفال والأسرة',
        relationships: 'العلاقات',
        trauma: 'الصدمات والعنف',
        neurodiversity: 'التوحد وفرط الحركة والتعلّم',
        addiction: 'الإدمان',
        work: 'العمل والاحتراق',
        wellbeing: 'العافية اليومية',
      },
      featured: 'مختارات',
      listen: 'استمع',
      read: 'اقرأ',
      otherLanguage: 'بالإنجليزية',
      article: 'مقال',
      podcast: 'بودكاست',
      opensIn: 'يُفتح داخل هُنا',
      empty: 'لا شيء يطابق بعد. جرّب كلمة أو موضوعًا آخر.',
      loading: 'جاري التحميل…',
      error: 'تعذّر تحميل المقالات والبودكاست',
    },
    wellnessCenters: {
      title: 'مراكز العافية',
      searchPlaceholder: 'ابحث في المراكز أو الخدمات',
      badge: 'مركز عافية',
      loading: 'جاري تحميل مراكز العافية...',
      error: 'فشل تحميل مراكز العافية',
      loadingDetail: 'جاري تحميل مركز العافية...',
      errorDetail: 'فشل تحميل مركز العافية',
      count: { one: 'مركز عافية واحد', two: 'مركزا عافية', few: '{n} مراكز عافية', many: '{n} مركز عافية' },
    },
    articles: {
      title: 'المقالات',
      loading: 'جاري تحميل المقالات...',
      error: 'فشل تحميل المقالات',
      count: { one: 'مقالة واحدة', two: 'مقالتان', few: '{n} مقالات', many: '{n} مقالة' },
    },
    podcasts: {
      title: 'البودكاست',
      loading: 'جاري تحميل حلقات البودكاست...',
      error: 'فشل تحميل حلقات البودكاست',
      count: { one: 'حلقة واحدة', two: 'حلقتان', few: '{n} حلقات', many: '{n} حلقة' },
    },
    resources: {
      loading: 'جاري تحميل الدليل...',
      error: 'فشل تحميل الدليل',
      learnMore: 'اعرف المزيد',
      intro: 'أدلة واضحة ولطيفة لمواضيع الصحة النفسية الشائعة: ما هي، وما الذي يساعد، وأين تجد الدعم.',
      topicCount: { one: 'موضوع واحد', two: 'موضوعان', few: '{n} مواضيع', many: '{n} موضوعًا' },
      detailLoading: 'جاري تحميل الموضوع...',
      detailError: 'فشل تحميل الموضوع',
      noContent: 'لا يوجد محتوى متاح لهذا الموضوع.',
      topicEyebrow: 'موضوع في الصحة النفسية',
      sectionsLabel: 'الأقسام',
    },
  },
} as const;
