/**
 * Tanafas hub tabs (Breathe · Meditate · Discover) and the self-reflection
 * flow (canvas "Tanafas", "Self-reflection — question / results"). English
 * is the canvas copy; the disclaimer is FEATURES_BRIEF §5's wording and
 * must appear before and after every test.
 */
export const discoverStrings = {
  en: {
    hub: {
      close: 'Close Tanafas',
      journal: 'Journal',
      tabsLabel: 'Tanafas',
      tabs: { breathe: 'Breathe', meditate: 'Meditate', discover: 'Discover' },
      previous: 'Previous',
      next: 'Next',
      begin: 'Begin',
      safetyNote: 'A safety check appears before every session.',
      pattern: 'Pattern',
      duration: 'Duration',
      video: 'Video',
      noLimit: 'No limit',
      custom: 'Custom',
      fewerMinutes: 'A minute less',
      moreMinutes: 'A minute more',
      hours: 'Hours',
      minutes: 'Minutes',
      customLimit: 'From 1 minute to {max} hours',
      on: 'On',
      off: 'Off',
      patterns: {
        anxietyRelief: '4 · 7 · 8',
        steadyMind: '4 · 4 · 4 · 4',
        panicRelief: 'Five senses',
        tensionRelease: 'Group by group',
        physiologicalSigh: '2 · 1 · 6',
      },
      ambientScene: 'Ambient scene',
      /** The Meditate tab's hero (canvas "Players — the Meditate tab as a hero"). */
      meditate: 'Meditate',
      scene: 'Scene',
      length: 'Length',
      chooseScene: 'Choose a scene',
      chooseSceneTitle: 'Choose a scene',
      choose: 'Choose {name}',
      // The scene sheet's button: choosing and starting in one step (canvas "Round 2 — the scene sheet").
      beginWith: { fire: 'Begin by the fire', rain: 'Begin with the rain', forest: 'Begin by the creek', ocean: 'Begin by the sea' },
      lengthTitle: 'How long?',
      done: 'Done',
      withVideo: 'Video and sound on · change them during the session',
      soundOnly: 'Sound only for this scene',
      /** A line to sit with for each scene, shown large on the hero. */
      sceneLines: {
        fire: 'Sit by the fire',
        rain: 'Listen to the rain',
        forest: 'Follow the creek',
        ocean: 'Drift with the sea',
      },
    },
    discover: {
      eyebrow: 'Short self-reflections',
      title: 'A gentle look inward',
      body: 'Short questionnaires to understand yourself a little better. Your results can be added to your profile.',
      disclaimer: "These aren't a diagnosis — just a peek inward. If something here resonates, a professional can help.",
      findProfessional: 'Find a professional',
      questions: { one: '{n} question', few: '{n} questions' },
      minutes: '~{n} min',
      empty: 'New self-reflections are on their way.',
    },
    test: {
      leave: 'Leave the questionnaire',
      begin: 'Begin',
      source: 'Source',
      disclaimer:
        "This is not a diagnosis — it's a gentle look inward. For a real assessment, or if anything here worries you, talk to a mental health professional.",
      progress: 'Question {i} of {n}',
      minutesLeft: '~{n} min left',
      answerLabel: 'Your answer',
      back: 'Back',
      next: 'Next',
      seeResults: 'See results',
      notFound: "This questionnaire isn't available.",
    },
    results: {
      close: 'Close results',
      eyebrow: 'Your results · {test}',
      title: 'A gentle look inward',
      findProfessional: 'Find a professional',
      staysOnPhone: 'Your results stay on this phone only. Find them any time in My results.',
      notFound: "These results aren't available.",
      score: 'Score {score} of {max}',
      support: {
        body: "You don't have to carry this alone. If things feel like too much right now, talk to someone today.",
        talkNow: 'Talk to someone now',
      },
    },
  },
  ar: {
    hub: {
      close: 'إغلاق تنفّس',
      journal: 'اليوميات',
      tabsLabel: 'تنفّس',
      tabs: { breathe: 'تنفّس', meditate: 'تأمّل', discover: 'اكتشف' },
      previous: 'السابق',
      next: 'التالي',
      begin: 'ابدأ',
      safetyNote: 'يظهر فحص أمان قبل كل جلسة.',
      pattern: 'النمط',
      duration: 'المدة',
      video: 'الفيديو',
      noLimit: 'بلا حد',
      custom: 'مدة مخصّصة',
      fewerMinutes: 'دقيقة أقل',
      moreMinutes: 'دقيقة أكثر',
      hours: 'الساعات',
      minutes: 'الدقائق',
      customLimit: 'من دقيقة واحدة حتى {max} ساعات',
      on: 'مفعّل',
      off: 'غير متاح',
      patterns: {
        anxietyRelief: '٤ · ٧ · ٨',
        steadyMind: '٤ · ٤ · ٤ · ٤',
        panicRelief: 'الحواس الخمس',
        tensionRelease: 'مجموعة تلو الأخرى',
        physiologicalSigh: '٢ · ١ · ٦',
      },
      ambientScene: 'مشهد محيطي',
      meditate: 'تأمّل',
      scene: 'المشهد',
      length: 'المدة',
      chooseScene: 'اختر مشهدًا',
      chooseSceneTitle: 'اختر مشهدًا',
      choose: 'اختر {name}',
      beginWith: { fire: 'لنبدأ قرب النار', rain: 'لنبدأ مع المطر', forest: 'لنبدأ قرب الجدول', ocean: 'لنبدأ قرب البحر' },
      lengthTitle: 'كم من الوقت؟',
      done: 'تم',
      withVideo: 'الفيديو والصوت يعملان · يمكنك تغييرهما أثناء الجلسة',
      soundOnly: 'صوت فقط لهذا المشهد',
      sceneLines: {
        fire: 'اجلس قرب النار',
        rain: 'أنصت للمطر',
        forest: 'اتبع الجدول',
        ocean: 'انجرف مع البحر',
      },
    },
    discover: {
      eyebrow: 'تأمّلات ذاتية قصيرة',
      title: 'نظرة لطيفة إلى الداخل',
      body: 'استبيانات قصيرة لتفهم نفسك أكثر قليلاً. يمكنك إضافة نتائجك إلى ملفك الشخصي.',
      disclaimer: 'هذه ليست تشخيصاً — بل نظرة سريعة إلى الداخل. إن لامسك شيء هنا، يمكن لمختص أن يساعدك.',
      findProfessional: 'ابحث عن مختص',
      questions: { one: 'سؤال واحد', two: 'سؤالان', few: '{n} أسئلة', many: '{n} سؤالاً' },
      minutes: '~{n} د',
      empty: 'تأمّلات ذاتية جديدة في الطريق.',
    },
    test: {
      leave: 'مغادرة الاستبيان',
      begin: 'ابدأ',
      source: 'المصدر',
      disclaimer:
        'هذا ليس تشخيصاً — بل نظرة لطيفة إلى الداخل. لتقييم حقيقي، أو إن أقلقك أي شيء هنا، تحدّث إلى مختص في الصحة النفسية.',
      progress: 'السؤال {i} من {n}',
      minutesLeft: '~{n} د متبقية',
      answerLabel: 'إجابتك',
      back: 'رجوع',
      next: 'التالي',
      seeResults: 'اعرض النتائج',
      notFound: 'هذا الاستبيان غير متاح.',
    },
    results: {
      close: 'إغلاق النتائج',
      eyebrow: 'نتائجك · {test}',
      title: 'نظرة لطيفة إلى الداخل',
      findProfessional: 'ابحث عن مختص',
      staysOnPhone: 'تبقى نتائجك على هذا الهاتف فقط. تجدها في أي وقت في «نتائجي».',
      notFound: 'هذه النتائج غير متاحة.',
      score: 'النتيجة {score} من {max}',
      support: {
        body: 'لست مضطراً لحمل هذا وحدك. إن شعرت أن الأمور أكبر من طاقتك الآن، تحدّث مع أحد اليوم.',
        talkNow: 'تحدّث مع أحد الآن',
      },
    },
  },
} as const;
