/**
 * Tanafas hub tabs (Breathe · Meditate · Discover) and the self-reflection
 * flow (canvas "Tanafas", "Self-reflection — question / results"). English
 * is the canvas copy; the disclaimer is FEATURES_BRIEF §5's wording and
 * must appear before and after every test.
 */
export const discoverStrings = {
  en: {
    hub: {
      close: 'Close Tanafas',
      journal: 'Journal',
      tabsLabel: 'Tanafas',
      tabs: { breathe: 'Breathe', meditate: 'Meditate', discover: 'Discover' },
      previous: 'Previous',
      next: 'Next',
      begin: 'Begin',
      safetyNote: 'A safety check appears before every session.',
      pattern: 'Pattern',
      duration: 'Duration',
      video: 'Video',
      noLimit: 'No limit',
      on: 'On',
      off: 'Off',
      patterns: {
        anxietyRelief: '4 · 7 · 8',
        steadyMind: '4 · 4 · 4 · 4',
        panicRelief: 'Five senses',
        nervousSystemReset: 'Breaths + hold',
        tensionRelease: 'Group by group',
      },
      ambientScene: 'Ambient scene',
    },
    discover: {
      eyebrow: 'Short self-reflections',
      title: 'A gentle look inward',
      body: 'Short questionnaires to understand yourself a little better. Your results can be added to your profile.',
      disclaimer: "These aren't a diagnosis — just a peek inward. If something here resonates, a professional can help.",
      findProfessional: 'Find a professional',
      questions: { one: '{n} question', few: '{n} questions' },
      minutes: '~{n} min',
      empty: 'New self-reflections are on their way.',
    },
    test: {
      leave: 'Leave the questionnaire',
      begin: 'Begin',
      source: 'Source',
      disclaimer:
        "This is not a diagnosis — it's a gentle look inward. For a real assessment, or if anything here worries you, talk to a mental health professional.",
      progress: 'Question {i} of {n}',
      minutesLeft: '~{n} min left',
      answerLabel: 'Your answer',
      back: 'Back',
      next: 'Next',
      seeResults: 'See results',
      notFound: "This questionnaire isn't available.",
    },
    results: {
      close: 'Close results',
      eyebrow: 'Your results · {test}',
      title: 'A gentle look inward',
      findProfessional: 'Find a professional',
      saveToProfile: 'Save to my profile',
      savedToProfile: 'Saved to your profile',
      saveFailed: "Couldn't save to your profile — please try again.",
      signInToSave: 'Sign in with an Alias to save results to your profile.',
      staysOnPhone: 'Results stay on this phone unless you save them.',
      notFound: "These results aren't available.",
    },
  },
  ar: {
    hub: {
      close: 'إغلاق تنفّس',
      journal: 'اليوميات',
      tabsLabel: 'تنفّس',
      tabs: { breathe: 'تنفّس', meditate: 'تأمّل', discover: 'اكتشف' },
      previous: 'السابق',
      next: 'التالي',
      begin: 'ابدأ',
      safetyNote: 'يظهر فحص أمان قبل كل جلسة.',
      pattern: 'النمط',
      duration: 'المدة',
      video: 'الفيديو',
      noLimit: 'بلا حد',
      on: 'مفعّل',
      off: 'غير متاح',
      patterns: {
        anxietyRelief: '٤ · ٧ · ٨',
        steadyMind: '٤ · ٤ · ٤ · ٤',
        panicRelief: 'الحواس الخمس',
        nervousSystemReset: 'أنفاس + حبس',
        tensionRelease: 'مجموعة تلو الأخرى',
      },
      ambientScene: 'مشهد محيطي',
    },
    discover: {
      eyebrow: 'تأمّلات ذاتية قصيرة',
      title: 'نظرة لطيفة إلى الداخل',
      body: 'استبيانات قصيرة لتفهم نفسك أكثر قليلاً. يمكنك إضافة نتائجك إلى ملفك الشخصي.',
      disclaimer: 'هذه ليست تشخيصاً — بل نظرة سريعة إلى الداخل. إن لامسك شيء هنا، يمكن لمختص أن يساعدك.',
      findProfessional: 'ابحث عن مختص',
      questions: { one: 'سؤال واحد', two: 'سؤالان', few: '{n} أسئلة', many: '{n} سؤالاً' },
      minutes: '~{n} د',
      empty: 'تأمّلات ذاتية جديدة في الطريق.',
    },
    test: {
      leave: 'مغادرة الاستبيان',
      begin: 'ابدأ',
      source: 'المصدر',
      disclaimer:
        'هذا ليس تشخيصاً — بل نظرة لطيفة إلى الداخل. لتقييم حقيقي، أو إن أقلقك أي شيء هنا، تحدّث إلى مختص في الصحة النفسية.',
      progress: 'السؤال {i} من {n}',
      minutesLeft: '~{n} د متبقية',
      answerLabel: 'إجابتك',
      back: 'رجوع',
      next: 'التالي',
      seeResults: 'اعرض النتائج',
      notFound: 'هذا الاستبيان غير متاح.',
    },
    results: {
      close: 'إغلاق النتائج',
      eyebrow: 'نتائجك · {test}',
      title: 'نظرة لطيفة إلى الداخل',
      findProfessional: 'ابحث عن مختص',
      saveToProfile: 'احفظ في ملفي الشخصي',
      savedToProfile: 'حُفظت في ملفك الشخصي',
      saveFailed: 'تعذّر الحفظ في ملفك الشخصي — يرجى المحاولة مرة أخرى.',
      signInToSave: 'سجّل الدخول باسم مستعار لحفظ النتائج في ملفك الشخصي.',
      staysOnPhone: 'تبقى النتائج على هذا الهاتف ما لم تحفظها.',
      notFound: 'هذه النتائج غير متاحة.',
    },
  },
} as const;
