/**
 * Journal + mood tracker strings. Ported from the old MVP's JournalScreen,
 * JournalEntryScreen and MoodHistoryScreen (see houna-port-reference.md).
 *
 * Two deliberate departures from the old MVP, both flagged to the user:
 * - "Share as Image" (Canvas-rendered aged-paper image) isn't portable to
 *   RN as-is; replaced with plain-text sharing (`entry.share`) of a single
 *   entry via the native share sheet, plus a real bulk JSON export
 *   (`list.export*`) for on-device backup — the actual data-loss protection
 *   CLAUDE.md asks for.
 * - `moodLabels` (short) vs `moodLabelsFull` (long) is an asymmetry that
 *   already existed in the old MVP (mood picker uses the short AR label,
 *   insights uses the full one) — preserved as-is rather than "fixed".
 */
import type { MoodTag } from '@/lib/journal';

export const journalStrings = {
  en: {
    list: {
      badge: 'Personal Journal',
      title: 'Your Journal',
      subtitle: 'A private space for your thoughts. Only you can see what you write here.',
      newEntry: 'New Entry',
      emptyTitle: 'Your journal is empty',
      emptyBody: "Write your first entry whenever you're ready. There's no pressure — this is your space.",
      tabEntries: 'Entries',
      tabInsights: 'Insights',
      noText: 'No text',
      exportAction: 'Export your entries',
      exportError: 'Could not export — please try again',
    },
    entry: {
      newEntry: 'New Entry',
      editEntry: 'Edit Entry',
      yourEntry: 'Your Entry',
      save: 'Save Entry',
      edit: 'Edit Entry',
      share: 'Share Entry',
      skipPrompt: 'Skip prompt',
      writeFreely: 'Write freely instead',
      howFeeling: 'How are you feeling?',
      discardTitle: 'Discard this entry?',
      discardBody: "Your writing will be lost and can't be recovered.",
      keepWriting: 'Keep writing',
      discard: 'Discard',
      deleteTitle: 'Delete this entry?',
      deleteBody: 'This entry will be permanently removed from your journal.',
      cancel: 'Cancel',
      delete: 'Delete',
      placeholder: 'Write whatever comes to mind…',
      shareError: 'Could not share — please try again',
    },
    dateNames: {
      weekdaysShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
      weekdaysLong: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
      monthsShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      monthsLong: [
        'January', 'February', 'March', 'April', 'May', 'June',
        'July', 'August', 'September', 'October', 'November', 'December',
      ],
    },
    insights: {
      badge: 'Mood Insights',
      title: 'Your Mood Trend',
      subtitle: 'See how your mood has shifted over time.',
      sevenDays: '7 Days',
      thirtyDays: '30 Days',
      placeholder: (remaining: number) =>
        `Log ${remaining} more ${remaining === 1 ? 'mood' : 'moods'} to see your trend — ${remaining} to go!`,
      tapHint: 'Tap any point to see that day’s mood and journal entry.',
      noEntry: 'No mood logged this day.',
      preview: 'Journal preview',
      viewEntry: 'View full entry',
    },
    moodLabels: {
      angry: 'Angry',
      anxious: 'Anxious',
      sad: 'Sad',
      neutral: 'Neutral',
      calm: 'Calm',
      hopeful: 'Hopeful',
      joyful: 'Joyful',
      // Retired from the check-in; older entries can still hold them.
      frustrated: 'Frustrated',
      tired: 'Tired',
    } as Record<MoodTag, string>,
    moodLabelsFull: {
      angry: 'Angry',
      anxious: 'Anxious',
      sad: 'Sad',
      neutral: 'Neutral',
      calm: 'Calm',
      hopeful: 'Hopeful',
      joyful: 'Joyful',
      // Retired from the check-in; older entries can still hold them.
      frustrated: 'Frustrated',
      tired: 'Tired',
    } as Record<MoodTag, string>,
    prompts: [
      "What's one thing on your mind today?",
      'How are you feeling right now, and why?',
      'What is something you are grateful for today?',
      'What brought you a moment of peace today?',
      'Is there anything you would like to let go of?',
      'What is one small thing that went well today?',
      'How would you describe today in a single word, and why that word?',
    ],
  },
  ar: {
    list: {
      badge: 'يوميات شخصية',
      title: 'يومياتك',
      subtitle: 'مساحة خاصة لأفكارك. أنت وحدك تستطيع رؤية ما تكتبه هنا.',
      newEntry: 'مدخل جديد',
      emptyTitle: 'يومياتك فارغة',
      emptyBody: 'اكتب أول مدخل عندما تكون مستعداً. لا ضغط — هذه مساحتك.',
      tabEntries: 'المدخلات',
      tabInsights: 'سجل المزاج',
      noText: 'لا يوجد نص',
      exportAction: 'تصدير مدخلاتك',
      exportError: 'تعذّر التصدير — يرجى المحاولة مرة أخرى',
    },
    entry: {
      newEntry: 'مدخل جديد',
      editEntry: 'تعديل',
      yourEntry: 'مدخلك',
      save: 'حفظ',
      edit: 'تعديل',
      share: 'مشاركة المدخل',
      skipPrompt: 'تخطي',
      writeFreely: 'الكتابة بحرية',
      howFeeling: 'كيف تشعر؟',
      discardTitle: 'هل تريد حذف هذا المدخل؟',
      discardBody: 'كتابتك ستُفقد ولا يمكن استرجاعها.',
      keepWriting: 'متابعة الكتابة',
      discard: 'حذف',
      deleteTitle: 'حذف هذا المدخل؟',
      deleteBody: 'سيُزال هذا المدخل نهائياً من يومياتك.',
      cancel: 'إلغاء',
      delete: 'حذف',
      placeholder: 'اكتب ما يدور في ذهنك…',
      shareError: 'تعذّرت المشاركة — يرجى المحاولة مرة أخرى',
    },
    dateNames: {
      weekdaysShort: ['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'],
      weekdaysLong: ['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'],
      monthsShort: ['يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'],
      monthsLong: ['يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'],
    },
    insights: {
      badge: 'رؤى المزاج',
      title: 'اتجاه مزاجك',
      subtitle: 'شاهد كيف تغير مزاجك مع مرور الوقت.',
      sevenDays: '٧ أيام',
      thirtyDays: '٣٠ يوماً',
      placeholder: (remaining: number) => `سجّل ${remaining} مزاج آخر لرؤية اتجاهك — تبقّى ${remaining}!`,
      tapHint: 'اضغط على أي نقطة لرؤية مزاج ذلك اليوم ومدخل اليوميات.',
      noEntry: 'لا يوجد مزاج مسجّل لهذا اليوم.',
      preview: 'معاينة اليوميات',
      viewEntry: 'عرض المدخل كاملاً',
    },
    moodLabels: {
      angry: 'غاضب',
      anxious: 'قلق',
      sad: 'حزين',
      neutral: 'محايد',
      calm: 'هادئ',
      hopeful: 'متفائل',
      joyful: 'مبتهج',
      // Retired from the check-in; older entries can still hold them.
      frustrated: 'محبط',
      tired: 'متعب',
    } as Record<MoodTag, string>,
    moodLabelsFull: {
      angry: 'غاضب',
      anxious: 'قلق',
      sad: 'حزين',
      neutral: 'محايد',
      calm: 'هادئ',
      hopeful: 'متفائل',
      joyful: 'مبتهج',
      // Retired from the check-in; older entries can still hold them.
      frustrated: 'محبط',
      tired: 'متعب',
    } as Record<MoodTag, string>,
    prompts: [
      'ما الشيء الذي يشغل بالك اليوم؟',
      'كيف تشعر الآن، ولماذا؟',
      'ما الشيء الذي تشعر بالامتنان له اليوم؟',
      'ما الذي منحك لحظة من السلام اليوم؟',
      'هل هناك شيء تود أن تتركه خلفك؟',
      'ما الشيء الصغير الذي سار على ما يرام اليوم؟',
      'كيف تصف اليوم بكلمة واحدة، ولماذا هذه الكلمة؟',
    ],
  },
};
