/**
 * Profile (canvas "Profile"), opened from Home's top-right button. English
 * is the canvas copy.
 */
export const profileStrings = {
  en: {
    title: 'Profile',
    back: 'Back to Home',
    edit: 'Edit',
    addCountry: 'Add your country',
    // Phase 6 (canvas "Phase 6 — Profile: the Kufic ring").
    since: 'With Houna since {month}',
    numbers: { streak: 'Day streak', month: 'This month', badges: 'Badges' },
    badgesCard: { seeAll: 'See all' },
    sky: {
      eyebrow: 'Your sky · {month}',
      stars: { one: '{n} star so far', few: '{n} stars so far' },
      empty: 'Your next session places the first star.',
      line: 'One for each day you practised, joined in order. Tonight’s joins the rest.',
      tap: 'Tap a star for its day. A new month begins a new sky.',
      open: 'Your sky: {n}',
      minutes: { one: '{n} min', few: '{n} min' },
    },
    breath: {
      title: 'Your month in breath',
      empty: 'This month’s practice will rise here.',
      a11y: '{month}: {n} in all.',
    },
    rows: { results: 'My results', recap: 'Recap · {month}', stats: 'Stats & leaderboard' },
    recap: {
      eyebrow: 'Your {month} recap',
      title: 'See your month in Houna',
    },
    traits: {
      eyebrow: 'Your traits',
      from: 'From {test}',
      taken: 'Taken {date} · not a diagnosis',
      view: 'View results',
    },
    streak: {
      title: { one: '{n}-day practice streak', few: '{n}-day practice streak' },
      none: 'Your practice streak starts with your next session',
      note: 'Breathing and meditation only — never mood',
      stats: 'Stats',
    },
    guest: {
      title: "You're browsing as a guest",
      body: 'Claim an alias — no real name or email needed — to keep your streak and results in one place.',
      signIn: 'Sign in',
      createAlias: 'Create alias',
      deleted: 'Your Alias has been deleted.',
    },
    settings: {
      language: 'Language',
      appearance: 'Appearance',
      appearanceOptions: { sunrise: 'Sunrise', day: 'Dusk', night: 'Night' },
      // Both Home styles kept while the client decides (ThemeContext HomeStyle).
      homeStyle: 'Home',
      homeStyleOptions: { sky: 'Sun & moon', classic: 'Classic' },
      // Sunrise's accent while it's decided (constants/theme.ts SunriseAccent).
      sunriseAccent: 'Sunrise accent',
      sunriseAccentOptions: { dark: 'Dark', mixed: 'Mixed', turquoise: 'Turquoise' },
      notifications: 'Notifications',
      communityMap: 'Community map',
      exportJournal: 'Export my journal',
      exportError: 'Could not export — please try again.',
    },
    signOut: 'Sign out',
  },
  ar: {
    title: 'الملف الشخصي',
    back: 'العودة إلى الرئيسية',
    edit: 'تعديل',
    addCountry: 'أضف دولتك',
    since: 'معنا منذ {month}',
    numbers: { streak: 'السلسلة', month: 'هذا الشهر', badges: 'الشارات' },
    badgesCard: { seeAll: 'كلها' },
    sky: {
      eyebrow: 'سماؤك · {month}',
      stars: { one: 'نجمة واحدة حتى الآن', two: 'نجمتان حتى الآن', few: '{n} نجوم حتى الآن', many: '{n} نجمة حتى الآن' },
      empty: 'الجلسة القادمة تضع أول نجمة.',
      line: 'نجمة لكل يوم ممارسة، موصولة بالترتيب. نجمة الليلة تنضمّ إليها.',
      tap: 'اضغط نجمة لترى يومها. يبدأ شهر جديد بسماء جديدة.',
      open: 'سماؤك: {n}',
      minutes: { one: 'دقيقة واحدة', two: 'دقيقتان', few: '{n} دقائق', many: '{n} دقيقة' },
    },
    breath: {
      title: 'شهرك في أنفاس',
      empty: 'ستظهر ممارسة هذا الشهر هنا.',
      a11y: '{month}: {n} في المجموع.',
    },
    rows: { results: 'نتائجي', recap: 'ملخص {month}', stats: 'الإحصاءات والمتصدرون' },
    recap: {
      eyebrow: 'ملخّص {month}',
      title: 'شاهد شهرك في هُنا',
    },
    traits: {
      eyebrow: 'سماتك',
      from: 'من {test}',
      taken: 'أُجري في {date} · ليس تشخيصاً',
      view: 'اعرض النتائج',
    },
    streak: {
      title: {
        one: 'سلسلة ممارسة ليوم واحد',
        two: 'سلسلة ممارسة ليومين',
        few: 'سلسلة ممارسة لـ{n} أيام',
        many: 'سلسلة ممارسة لـ{n} يوماً',
      },
      none: 'تبدأ سلسلة ممارستك مع جلستك القادمة',
      note: 'التنفّس والتأمّل فقط — وليس المزاج أبداً',
      stats: 'الإحصاءات',
    },
    guest: {
      title: 'أنت تتصفّح كضيف',
      body: 'اختر اسماً مستعاراً — دون اسم حقيقي أو بريد إلكتروني — لتحتفظ بسلسلتك ونتائجك في مكان واحد.',
      signIn: 'تسجيل الدخول',
      createAlias: 'إنشاء اسم مستعار',
      deleted: 'حُذف اسمك المستعار.',
    },
    settings: {
      language: 'اللغة',
      appearance: 'المظهر',
      appearanceOptions: { sunrise: 'الشروق', day: 'الغسق', night: 'ليلي' },
      homeStyle: 'الرئيسية',
      homeStyleOptions: { sky: 'الشمس والقمر', classic: 'الكلاسيكي' },
      sunriseAccent: 'لون الشروق',
      sunriseAccentOptions: { dark: 'داكن', mixed: 'مختلط', turquoise: 'فيروزي' },
      notifications: 'الإشعارات',
      communityMap: 'خريطة المجتمع',
      exportJournal: 'تصدير يومياتي',
      exportError: 'تعذّر التصدير — يرجى المحاولة مرة أخرى.',
    },
    signOut: 'تسجيل الخروج',
  },
} as const;
