/**
 * Strings for the Tanafas feature (hub, breathing & grounding list, and the
 * five exercise screens). Split out from constants/strings.ts because of
 * sheer size — merged into the main catalogue's `tanafas` key.
 *
 * Ported from the old MVP wherever it already had the content
 * (../../reference/old-mvp/src/screens/{CalmScreen,BreathingExerciseScreen,
 * SteadyMindBreathingScreen,PanicReliefGroundingScreen,
 * NervousSystemResetScreen,TensionReleaseScreen}.tsx). Panic Relief
 * Grounding had no Arabic in the old MVP — that one's translated fresh,
 * marked below.
 */

import { meditationStrings } from './meditationStrings';
import { voicesStrings } from './voicesStrings';

export const tanafasStrings = {
  en: {
    hub: {
      title: 'Tanafas',
      subtitle: 'Take a moment for yourself',
      breathingTitle: 'Breathing & Grounding',
      breathingSubtitle: '5 guided exercises',
      breathingDescription: 'Breathing techniques, grounding, and muscle relaxation to help you find calm.',
      meditationTitle: 'Meditation',
      meditationSubtitle: 'Ambient scenes & guided sessions',
      meditationDescription: 'Calming soundscapes and guided sessions to help you unwind.',
      journalTitle: 'Journal',
      journalSubtitle: 'Write freely, reflect privately',
      journalDescription: 'A private space to capture your thoughts and mood, stored only on your device.',
      comingSoonTitle: 'Coming Soon',
      comingSoonBody: (name: string) => `${name} is being crafted with care and will be available in a future update.`,
      gotIt: 'Got it',
      storyOfWeek: 'Story of the Week',
    },
    breathingList: {
      title: 'Breathing & Grounding',
      subtitle: 'Choose a guided exercise below to help you find your calm.',
      soon: 'Soon',
    },
    // Vocabulary shared by the phase-cycling exercises (4-7-8, Box breathing).
    session: {
      chooseSession: 'Choose your session length',
      min: 'min',
      minPlural: 'min',
      round: 'Round',
      ofTotal: 'of',
      ready: 'Ready when you are',
      wellDone: 'Well done',
      completedPrefix: 'You completed',
      roundSingular: 'round',
      roundPlural: 'rounds',
      begin: 'Begin',
      pause: 'Pause',
      resume: 'Resume',
      startAgain: 'Start Again',
      exit: 'Exit',
      remainingSuffix: 's remaining',
      sec: 's',
    },
    exercises: {
      anxietyRelief: {
        title: 'Anxiety Relief Breathing',
        subtitle: '4-7-8 Breathing Technique',
        description: 'A structured breathing pattern that calms the nervous system and eases racing thoughts.',
        duration: '1-5 min',
        inhale: 'Inhale',
        hold: 'Hold',
        exhale: 'Exhale',
        completionBody: 'Take a moment to notice how you feel. Your nervous system has had a chance to reset. You can do another session whenever you need.',
      },
      steadyMind: {
        title: 'Steady Mind Breathing',
        subtitle: 'Box / 4x4 Breathing Technique',
        description: 'Equal inhale, hold, exhale, and hold to steady your mind and regain focus.',
        duration: '1-5 min',
        inhale: 'Inhale',
        hold: 'Hold',
        exhale: 'Exhale',
        completionBody: "Box breathing balances your nervous system and sharpens your focus. Sit quietly for a moment and notice the steadiness you've created. You can return to this practice whenever you need it.",
      },
      panicRelief: {
        title: 'Panic Relief Grounding',
        subtitle: '5-4-3-2-1 Senses Exercise',
        description: 'Reconnect with your surroundings to interrupt panic attacks and spiraling thoughts.',
        duration: '3 min',
        takeYourTime: 'Take your time — look around and name each one',
        stepCounter: (step: number, total: number, sense: string) => `Step ${step} of ${total} · ${sense}`,
        next: 'Next',
        finish: 'Finish',
        startAgain: 'Start Again',
        exit: 'Exit',
        completionTitle: 'Well done',
        completionSubtitle: "You've completed the grounding exercise",
        completionBody: "By naming what you see, touch, hear, smell, and taste, you've brought your attention back to the present moment. Panic thrives on the future and the past — you've just anchored yourself in the here and now. Stay with this awareness for as long as you need.",
        steps: [
          { count: 5, sense: 'See', prompt: 'Name 5 things you can see' },
          { count: 4, sense: 'Touch', prompt: 'Name 4 things you can touch' },
          { count: 3, sense: 'Hear', prompt: 'Name 3 things you can hear' },
          { count: 2, sense: 'Smell', prompt: 'Name 2 things you can smell' },
          { count: 1, sense: 'Taste', prompt: 'Name 1 thing you can taste' },
        ],
      },
      nervousSystemReset: {
        title: 'Nervous System Reset',
        subtitle: '(Wim Hof Method)',
        description: 'Powerful rhythmic breathing to build stress resilience and mental clarity.',
        duration: '5-15 min',
        cancel: 'Cancel',
        pleaseRead: 'Please read before you begin',
        warningBody: 'Do not practice this technique while driving, in or near water, standing up, or if you are pregnant or have a seizure disorder or cardiovascular condition. Always practice sitting or lying down in a safe space.',
        iUnderstand: 'I Understand',
        exit: 'Exit',
        sessionOverview: '3 rounds · progressive hold build-up',
        roundN: 'Round',
        holdSuffix: 's hold',
        round: 'Round',
        ofTotal: 'of',
        breathe: 'Breathe',
        hold: 'Hold',
        recoveryBreath: 'Recovery Breath',
        target: 'target',
        ready: 'Ready when you are',
        breatheGuide: "Take 30 deep, rhythmic breaths. Inhale fully through the nose or mouth, then let the exhale go passively — don't force it out.",
        holdGuide: 'After your last exhale, hold on empty lungs. The target is a guide — tap below whenever you feel the urge to breathe.',
        imDoneHolding: "I'm Done Holding",
        recoveryGuide: 'Take a full breath in and hold it. Feel the energy spread through your body.',
        holdTheBreathIn: 'Hold the breath in',
        wellDone: 'Well done',
        completedAll: 'You completed all 3 rounds',
        completionBody: "You've flooded your body with oxygen and activated your nervous system. Take a quiet moment to notice the clarity and calm. Return whenever you need a reset.",
        begin: 'Begin',
        pause: 'Pause',
        resume: 'Resume',
        startAgain: 'Start Again',
        sec: 's',
      },
      tensionRelease: {
        title: 'Tension Release',
        subtitle: 'Progressive Muscle Relaxation',
        description: 'Systematically release physical tension held in the body, group by group.',
        duration: '5 min',
        exit: 'Exit',
        tense: 'Tense',
        release: 'Release',
        holdTight: 'Hold tight',
        letGo: 'Let go',
        groupOf: 'Group',
        ofTotal: 'of',
        paused: 'Paused',
        wellDone: 'Well done',
        releasedTension: "You've released the tension",
        completionBody: "You've moved through your whole body, tensing and then letting go of each muscle group. Notice the deep, heavy stillness that remains. Let this softness stay with you as you carry on with your day.",
        startAgain: 'Start Again',
        next: 'Next',
        finish: 'Finish',
        groups: [
          { name: 'Hands & Fists', tensePrompt: 'Squeeze your hands into tight fists. Press your fingers into your palms and feel the tension build.', releasePrompt: 'Now let your hands go completely loose. Feel the tension drain away as your fingers uncurl.' },
          { name: 'Arms', tensePrompt: 'Bend your elbows and tense your biceps and forearms. Hold the tightness firmly.', releasePrompt: 'Release your arms and let them fall heavy and relaxed. Notice the warmth spreading through them.' },
          { name: 'Shoulders', tensePrompt: 'Pull your shoulders up toward your ears. Squeeze them tight and hold the tension.', releasePrompt: 'Let your shoulders drop away from your ears. Feel the weight lift and the tightness melt.' },
          { name: 'Face', tensePrompt: 'Scrunch your face — squeeze your eyes shut, wrinkle your nose, and clench your jaw.', releasePrompt: 'Release every part of your face. Let your jaw soften, your eyes gently close, your forehead smooth.' },
          { name: 'Chest & Stomach', tensePrompt: 'Tighten your chest and stomach muscles. Hold your core firm and feel the tension gather.', releasePrompt: 'Let your chest and belly soften completely. Allow each breath to rise and fall without effort.' },
          { name: 'Legs', tensePrompt: 'Tense your thighs and calves. Straighten your legs and squeeze the muscles tight.', releasePrompt: 'Release your legs and let them grow heavy and warm. Feel the tension flow down and away.' },
          { name: 'Feet', tensePrompt: 'Curl your toes and tense your feet. Hold the tightness right down to the tips of your toes.', releasePrompt: 'Let your feet go completely limp. Feel any last tension drain out through your toes.' },
        ],
      },
    },
    meditation: meditationStrings.en,
    voices: voicesStrings.en,
  },
  ar: {
    hub: {
      title: 'تنفّس',
      subtitle: 'خذ لحظة لنفسك',
      breathingTitle: 'تمارين التنفس والتأريض',
      breathingSubtitle: '٥ تمارين موجهة',
      breathingDescription: 'تقنيات تنفس وتأريض واسترخاء عضلي لمساعدتك على الهدوء.',
      meditationTitle: 'التأمل',
      meditationSubtitle: 'أجواء هادئة وجلسات موجهة',
      meditationDescription: 'أصوات مهدئة وجلسات موجهة تساعدك على الاسترخاء.',
      journalTitle: 'اليوميات',
      journalSubtitle: 'اكتب بحرية، تأمل بخصوصية',
      journalDescription: 'مساحة خاصة لتدوين أفكارك ومزاجك، محفوظة على جهازك فقط.',
      comingSoonTitle: 'قريباً',
      comingSoonBody: (name: string) => `يتم إعداد ${name} بعناية وستكون متاحة في تحديث قادم.`,
      gotIt: 'حسناً',
      storyOfWeek: 'قصة الأسبوع',
    },
    breathingList: {
      title: 'تمارين التنفس والتأريض',
      subtitle: 'اختر تمريناً موجهاً أدناه لمساعدتك على الشعور بالهدوء.',
      soon: 'قريباً',
    },
    session: {
      chooseSession: 'اختر مدة الجلسة',
      min: 'دقيقة',
      minPlural: 'دقائق',
      round: 'الجولة',
      ofTotal: 'من',
      ready: 'جاهز عندما تكون مستعداً',
      wellDone: 'أحسنت',
      completedPrefix: 'لقد أكملت',
      roundSingular: 'جولة',
      roundPlural: 'جولات',
      begin: 'ابدأ',
      pause: 'إيقاف مؤقت',
      resume: 'استئناف',
      startAgain: 'ابدأ من جديد',
      exit: 'رجوع',
      remainingSuffix: ' ثانية متبقية',
      sec: ' ثواني',
    },
    exercises: {
      anxietyRelief: {
        title: 'تمرين تهدئة القلق',
        subtitle: 'تقنية التنفس ٤-٧-٨',
        description: 'نمط تنفس منظم يهدئ الجهاز العصبي ويخفف الأفكار المتسارعة.',
        duration: '١-٥ دقائق',
        inhale: 'شهيق',
        hold: 'احتفاظ',
        exhale: 'زفير',
        completionBody: 'خذ لحظة لتلاحظ شعورك. لقد حصل جهازك العصبي على فرصة لإعادة الضبط. يمكنك القيام بجلسة أخرى متى احتجت.',
      },
      steadyMind: {
        title: 'تمرين ثبات العقل',
        subtitle: 'تقنية التنفس المربّع ٤×٤',
        description: 'شهيق وحبس وزفير وحبس بمقادير متساوية لتثبيت عقلك واستعادة تركيزك.',
        duration: '١-٥ دقائق',
        inhale: 'شهيق',
        hold: 'نكتم نفسنا',
        exhale: 'زفير',
        completionBody: 'خذ لحظة لتلاحظ شعورك. لقد ساعد هذا التمرين على تثبيت تركيزك وهدوئك. يمكنك القيام بجلسة أخرى متى احتجت.',
      },
      // No Arabic existed for this screen in the old MVP — translated fresh.
      panicRelief: {
        title: 'تمرين تهدئة الذعر',
        subtitle: 'تمرين الحواس ٥-٤-٣-٢-١',
        description: 'أعد الاتصال بما حولك لوقف نوبات الذعر والأفكار المتصاعدة.',
        duration: '٣ دقائق',
        takeYourTime: 'خذ وقتك — انظر حولك وسمِّ كل واحد',
        stepCounter: (step: number, total: number, sense: string) =>
          `الخطوة ${arabicNumberInline(step)} من ${arabicNumberInline(total)} · ${sense}`,
        next: 'التالي',
        finish: 'إنهاء',
        startAgain: 'ابدأ من جديد',
        exit: 'رجوع',
        completionTitle: 'أحسنت',
        completionSubtitle: 'لقد أكملت تمرين التأريض',
        completionBody: 'بتسمية ما تراه وتلمسه وتسمعه وتشمّه وتتذوقه، أعدت انتباهك إلى اللحظة الحاضرة. الذعر يتغذى على المستقبل والماضي — وأنت الآن راسخ في الهنا والآن. ابقَ مع هذا الوعي قدر ما تحتاج.',
        steps: [
          { count: 5, sense: 'البصر', prompt: 'سمِّ ٥ أشياء يمكنك رؤيتها' },
          { count: 4, sense: 'اللمس', prompt: 'سمِّ ٤ أشياء يمكنك لمسها' },
          { count: 3, sense: 'السمع', prompt: 'سمِّ ٣ أشياء يمكنك سماعها' },
          { count: 2, sense: 'الشم', prompt: 'سمِّ شيئين يمكنك شمّهما' },
          { count: 1, sense: 'التذوق', prompt: 'سمِّ شيئاً واحداً يمكنك تذوقه' },
        ],
      },
      nervousSystemReset: {
        title: 'إعادة ضبط الجهاز العصبي',
        subtitle: '(طريقة ويم هوف)',
        description: 'تنفس إيقاعي قوي لبناء المرونة تجاه التوتر ووضوح الذهن.',
        duration: '٥-١٥ دقيقة',
        cancel: 'إلغاء',
        pleaseRead: 'اقرأ قبل أن تبدأ',
        warningBody: 'لا تمارس هذا التمرين أثناء القيادة، أو في الماء أو بالقرب منه، أو أثناء الوقوف، أو إذا كنتِ حاملاً أو تعانين من اضطراب في النوبات أو حالة قلبية. مارسي التمرين دائماً في وضع الجلوس أو الاستلقاء في مكان آمن.',
        iUnderstand: 'أوافق',
        exit: 'رجوع',
        sessionOverview: '٣ جولات · زيادة تدريجية لمدة الحبس',
        roundN: 'الجولة',
        holdSuffix: ' ثانية حبس',
        round: 'الجولة',
        ofTotal: 'من',
        breathe: 'تنفّس',
        hold: 'نكتم نفسنا',
        recoveryBreath: 'نفس الاستشفاء',
        target: 'الهدف',
        ready: 'جاهز عندما تكون مستعداً',
        breatheGuide: 'خذ ٣٠ نفساً عميقاً وإيقاعياً. استنشق بعمق من الأنف أو الفم، ثم دع الزفير يمر بحرية — لا تطرده بالقوة.',
        holdGuide: 'بعد آخر زفير، احبس نفسك برئتين فارغتين. الهدف هو دليل فقط — اضغط أدناه متى شعرت بالحاجة للتنفس.',
        imDoneHolding: 'انتهيت من الحبس',
        recoveryGuide: 'خذ نفساً كاملاً واستنشق واحتفظ به. اشعر بالطاقة تنتشر في جسدك.',
        holdTheBreathIn: 'نفس الاستشفاء — احتفاظ',
        wellDone: 'أحسنت',
        completedAll: 'لقد أكملت جميع الجولات الثلاث',
        completionBody: 'خذ لحظة لتلاحظ شعورك. لقد منحت جسدك وعقلك فرصة قوية لإعادة الضبط. يمكنك القيام بجلسة أخرى متى احتجت.',
        begin: 'ابدأ',
        pause: 'إيقاف مؤقت',
        resume: 'استئناف',
        startAgain: 'ابدأ من جديد',
        sec: ' ثواني',
      },
      tensionRelease: {
        title: 'تحرير التوتر',
        subtitle: 'الاسترخاء العضلي التدريجي',
        description: 'حرر التوتر الجسدي المختزن في الجسم بشكل منهجي، مجموعة عضلية تلو الأخرى.',
        duration: '٥ دقائق',
        exit: 'رجوع',
        tense: 'شدّ',
        release: 'إرخاء',
        holdTight: 'احتفظ بالشدّ',
        letGo: 'أرخِ',
        groupOf: 'المجموعة',
        ofTotal: 'من',
        paused: 'متوقف مؤقتاً',
        wellDone: 'أحسنت',
        releasedTension: 'لقد تحرر جسدك من التوتر',
        completionBody: 'لقد حرر جسدك الكثير من التوتر المكتوم. خذ لحظة لتشعر بهذا الاسترخاء. يمكنك تكرار هذا التمرين متى احتجت.',
        startAgain: 'ابدأ من جديد',
        next: 'التالي',
        finish: 'إنهاء',
        groups: [
          { name: 'اليدان والقبضتان', tensePrompt: 'اقبض يديك بقوة لتكوّن قبضتين. اضغط بأصابعك على راحتيك واشعر بالتوتر يتزايد.', releasePrompt: 'والآن أرخهما تماماً. اشعر بالتوتر ينصرف بينما تنفرج أصابعك.' },
          { name: 'الذراعان', tensePrompt: 'شدّ عضلات ذراعيك بإحكام. احتفظ بهذا الشد بقوة.', releasePrompt: 'والآن دعهما يرتخيان تماماً. لاحظ الدفء ينتشر فيهما.' },
          { name: 'الكتفان', tensePrompt: 'ارفع كتفيك نحو أذنيك وشدّهما. اضغط عليهما بإحكام واحتفظ بالتوتر.', releasePrompt: 'والآن دعهما ينزلان ويرتخيان. اشعر بالثقل يرتفع والتيبس يذوب.' },
          { name: 'الوجه', tensePrompt: 'شدّ عضلات وجهك بالكامل — أغلق عينيك بقوة، اُكمش أنفك، واضغط على فكّك.', releasePrompt: 'والآن أرخِ كل ملامح وجهك. دع فكّك يلين وعينيك تغمضان وجبهتك تنبسط.' },
          { name: 'الصدر والبطن', tensePrompt: 'شدّ عضلات صدرك وبطنك. اجعل منطقتك الوسطى مشدودة واشعر بالتوتر يتجمع.', releasePrompt: 'والآن دعهما يرتخيان مع الزفير. دع كل نفس يصعد ويهبط بلا جهد.' },
          { name: 'الساقان', tensePrompt: 'شدّ عضلات ساقيك بإحكام. مدّ ساقيك واضغط على العضلات بقوة.', releasePrompt: 'والآن دعهما يرتخيان تماماً. اشعر بالتوتر ينحدر ويتلاشى.' },
          { name: 'القدمان', tensePrompt: 'اقبض أصابع قدميك بشدة. احتفظ بالتيبس حتى أطراف أصابعك.', releasePrompt: 'والآن أرخهما تماماً. اشعر بأي توتر متبقٍّ ينصرف عبر أصابع قدميك.' },
        ],
      },
    },
    meditation: meditationStrings.ar,
    voices: voicesStrings.ar,
  },
} as const;

// Local helper so panicRelief.stepCounter above can render Arabic-Indic
// digits without importing the shared helper into a `const` initializer
// (avoids a circular/ordering headache in this const object literal).
function arabicNumberInline(n: number): string {
  const digits = ['٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩'];
  return String(n).replace(/\d/g, (d) => digits[Number(d)]);
}
