/**
 * Strings for Voices (Segment 6 of the accounts roadmap) — the Tanafas hub's
 * community forum: Alias-submitted written pieces and photos, manually
 * moderated before anything is public. No old-MVP equivalent — this feature
 * never existed before now, so the copy is new.
 */

export const voicesStrings = {
  en: {
    hubTitle: 'Voices',
    hubSubtitle: 'Shared by the community',
    hubDescription: 'Stories, notes, and photos shared by Houna’s community.',
    feedTitle: 'Voices',
    feedEmpty: 'No posts yet — be the first to share something.',
    mySubmissions: 'My Submissions',
    backToFeed: 'Back to Feed',
    submit: 'Submit',
    guestPromptTitle: 'Sign in to share',
    guestPromptBody: 'Create an Alias to post your own stories, notes, and photos.',
    signIn: 'Sign In',
    statusPending: 'Pending review',
    statusApproved: 'Published',
    statusRejected: 'Not published',
    submitTitle: 'Share Something',
    submitSubtitle: 'Reviewed before anyone else can see it — usually within a day or two.',
    titleLabel: 'Title (optional)',
    titlePlaceholder: 'Give it a title…',
    bodyLabel: 'Your words',
    bodyPlaceholder: "Share a story, a note, a reflection — anything you'd like.",
    photoLabel: 'Photo (optional)',
    addPhoto: 'Add a Photo',
    changePhoto: 'Change Photo',
    removePhoto: 'Remove',
    forMeditationLabel: 'Consider this photo for a meditation background',
    forMeditationBody: "If we use it, you'll be credited by your username.",
    submitAction: 'Submit for Review',
    submitting: 'Submitting…',
    submitError: 'Something went wrong — please try again.',
    emptyPostError: 'Add some words or a photo before submitting.',
    submittedTitle: 'Submitted',
    submittedBody: "We'll review it soon — you can check its status under My Submissions.",
    done: 'Done',
    withdraw: 'Withdraw',
    withdrawConfirmTitle: 'Withdraw this post?',
    withdrawConfirmBody: "This can't be undone.",
    cancel: 'Cancel',
    forMeditationBadge: 'Meditation candidate',
    photosPermission: 'Houna needs access to your photos to attach one to your post.',
  },
  ar: {
    hubTitle: 'أصوات',
    hubSubtitle: 'مشاركات من المجتمع',
    hubDescription: 'قصص وملاحظات وصور يشاركها مجتمع هُنا.',
    feedTitle: 'أصوات',
    feedEmpty: 'لا توجد منشورات بعد — كن أول من يشارك شيئًا.',
    mySubmissions: 'مشاركاتي',
    backToFeed: 'العودة للمنشورات',
    submit: 'مشاركة',
    guestPromptTitle: 'سجّل الدخول للمشاركة',
    guestPromptBody: 'أنشئ اسمًا مستعارًا لنشر قصصك وملاحظاتك وصورك.',
    signIn: 'تسجيل الدخول',
    statusPending: 'قيد المراجعة',
    statusApproved: 'منشور',
    statusRejected: 'غير منشور',
    submitTitle: 'شارك شيئًا',
    submitSubtitle: 'تتم مراجعته قبل أن يراه أي شخص آخر — عادةً خلال يوم أو يومين.',
    titleLabel: 'العنوان (اختياري)',
    titlePlaceholder: 'أضف عنوانًا…',
    bodyLabel: 'كلماتك',
    bodyPlaceholder: 'شارك قصة، ملاحظة، أو خاطرة — أي شيء تودّ مشاركته.',
    photoLabel: 'صورة (اختياري)',
    addPhoto: 'إضافة صورة',
    changePhoto: 'تغيير الصورة',
    removePhoto: 'إزالة',
    forMeditationLabel: 'اعتبار هذه الصورة كخلفية تأمل محتملة',
    forMeditationBody: 'إذا استخدمناها، سيُنسب لك الفضل باسم المستخدم الخاص بك.',
    submitAction: 'إرسال للمراجعة',
    submitting: 'جاري الإرسال…',
    submitError: 'حدث خطأ ما — يرجى المحاولة مرة أخرى.',
    emptyPostError: 'أضف بعض الكلمات أو صورة قبل الإرسال.',
    submittedTitle: 'تم الإرسال',
    submittedBody: 'سنراجعه قريبًا — يمكنك متابعة حالته ضمن مشاركاتي.',
    done: 'تم',
    withdraw: 'سحب',
    withdrawConfirmTitle: 'سحب هذا المنشور؟',
    withdrawConfirmBody: 'لا يمكن التراجع عن هذا.',
    cancel: 'إلغاء',
    forMeditationBadge: 'مرشّحة للتأمل',
    photosPermission: 'يحتاج هُنا إلى الوصول لصورك لإرفاق واحدة بمنشورك.',
  },
};
