/**
 * Strings for Voices (Segment 6 of the accounts roadmap) — the Tanafas hub's
 * community forum: Alias-submitted written pieces and photos, manually
 * moderated before anything is public. No old-MVP equivalent — this feature
 * never existed before now, so the copy is new.
 */

export const voicesStrings = {
  en: {
    hubTitle: 'Voices',
    hubSubtitle: 'Shared by the community',
    hubDescription: 'Stories, notes, and photos shared by Houna’s community.',
    feedTitle: 'Voices',
    feedEmpty: 'No posts yet — be the first to share something.',
    mySubmissions: 'My Submissions',
    backToFeed: 'Back to Feed',
    submit: 'Submit',
    guestPromptTitle: 'Sign in to share',
    guestPromptBody: 'Create an Alias to post your own stories, notes, and photos.',
    signIn: 'Sign In',
    statusPending: 'Pending review',
    statusApproved: 'Published',
    statusRejected: 'Not published',
    submitTitle: 'Share Something',
    submitSubtitle: 'Reviewed before anyone else can see it — usually within a day or two.',
    titleLabel: 'Title (optional)',
    titlePlaceholder: 'Give it a title…',
    bodyLabel: 'Your words',
    bodyPlaceholder: "Share a story, a note, a reflection — anything you'd like.",
    photoLabel: 'Photo (optional)',
    addPhoto: 'Add a Photo',
    changePhoto: 'Change Photo',
    removePhoto: 'Remove',
    forMeditationLabel: 'Consider this photo for a meditation background',
    forMeditationBody: "If we use it, you'll be credited by your username.",
    submitAction: 'Submit for Review',
    submitting: 'Submitting…',
    submitError: 'Something went wrong — please try again.',
    emptyPostError: 'Add some words or a photo before submitting.',
    submittedTitle: 'Submitted',
    submittedBody: "We'll review it soon — you can check its status under My Submissions.",
    done: 'Done',
    withdraw: 'Withdraw',
    withdrawConfirmTitle: 'Withdraw this post?',
    withdrawConfirmBody: "This can't be undone.",
    cancel: 'Cancel',
    forMeditationBadge: 'Meditation candidate',
    photosPermission: 'Houna needs access to your photos to attach one to your post.',
    // Report and block (store requirement for posts from the community).
    report: 'Report this post',
    reportTitle: 'What’s wrong with it?',
    reportReasons: {
      harmful: 'It could hurt someone, or talks about self-harm',
      harassment: 'Harassment or hate',
      spam: 'Spam or advertising',
      personal: 'It shares someone’s private information',
      other: 'Something else',
    },
    reportSent: 'Thank you. This post is hidden for you, and our team will review it.',
    reportFailed: 'The report couldn’t be sent. Check your connection and try again.',
    block: 'Block @{name}',
    blockConfirmTitle: 'Block @{name}?',
    blockConfirmBody: 'You won’t see their posts in Voices on this phone. You can unblock everyone later from Voices.',
    blocked: 'Blocked. You won’t see their posts on this phone.',
    blockedCount: { one: 'You’ve blocked {n} person', few: 'You’ve blocked {n} people' },
    unblockAll: 'Unblock everyone',
    guidelines: 'Posts are reviewed before they appear. Be kind, and never share anyone’s private details.',
  },
  ar: {
    hubTitle: 'أصوات',
    hubSubtitle: 'مشاركات من المجتمع',
    hubDescription: 'قصص وملاحظات وصور يشاركها مجتمع هُنا.',
    feedTitle: 'أصوات',
    feedEmpty: 'لا توجد منشورات بعد — كن أول من يشارك شيئًا.',
    mySubmissions: 'مشاركاتي',
    backToFeed: 'العودة للمنشورات',
    submit: 'مشاركة',
    guestPromptTitle: 'سجّل الدخول للمشاركة',
    guestPromptBody: 'أنشئ اسمًا مستعارًا لنشر قصصك وملاحظاتك وصورك.',
    signIn: 'تسجيل الدخول',
    statusPending: 'قيد المراجعة',
    statusApproved: 'منشور',
    statusRejected: 'غير منشور',
    submitTitle: 'شارك شيئًا',
    submitSubtitle: 'تتم مراجعته قبل أن يراه أي شخص آخر — عادةً خلال يوم أو يومين.',
    titleLabel: 'العنوان (اختياري)',
    titlePlaceholder: 'أضف عنوانًا…',
    bodyLabel: 'كلماتك',
    bodyPlaceholder: 'شارك قصة، ملاحظة، أو خاطرة — أي شيء تودّ مشاركته.',
    photoLabel: 'صورة (اختياري)',
    addPhoto: 'إضافة صورة',
    changePhoto: 'تغيير الصورة',
    removePhoto: 'إزالة',
    forMeditationLabel: 'اعتبار هذه الصورة كخلفية تأمل محتملة',
    forMeditationBody: 'إذا استخدمناها، سيُنسب لك الفضل باسم المستخدم الخاص بك.',
    submitAction: 'إرسال للمراجعة',
    submitting: 'جاري الإرسال…',
    submitError: 'حدث خطأ ما — يرجى المحاولة مرة أخرى.',
    emptyPostError: 'أضف بعض الكلمات أو صورة قبل الإرسال.',
    submittedTitle: 'تم الإرسال',
    submittedBody: 'سنراجعه قريبًا — يمكنك متابعة حالته ضمن مشاركاتي.',
    done: 'تم',
    withdraw: 'سحب',
    withdrawConfirmTitle: 'سحب هذا المنشور؟',
    withdrawConfirmBody: 'لا يمكن التراجع عن هذا.',
    cancel: 'إلغاء',
    forMeditationBadge: 'مرشّحة للتأمل',
    photosPermission: 'يحتاج هُنا إلى الوصول لصورك لإرفاق واحدة بمنشورك.',
    report: 'الإبلاغ عن هذا المنشور',
    reportTitle: 'ما المشكلة فيه؟',
    reportReasons: {
      harmful: 'قد يؤذي أحدًا، أو يتحدث عن إيذاء النفس',
      harassment: 'تحرّش أو كراهية',
      spam: 'رسائل مزعجة أو إعلانات',
      personal: 'يكشف معلومات خاصة عن أحد',
      other: 'شيء آخر',
    },
    reportSent: 'شكرًا لك. أُخفي هذا المنشور عنك، وسيراجعه فريقنا.',
    reportFailed: 'تعذّر إرسال البلاغ. تحقّق من اتصالك وحاول مرة أخرى.',
    block: 'حظر @{name}',
    blockConfirmTitle: 'حظر @{name}؟',
    blockConfirmBody: 'لن ترى منشوراته في «أصوات» على هذا الهاتف. يمكنك إلغاء حظر الجميع لاحقًا من «أصوات».',
    blocked: 'تم الحظر. لن ترى منشوراته على هذا الهاتف.',
    blockedCount: { one: 'حظرتَ شخصًا واحدًا', two: 'حظرتَ شخصين', few: 'حظرتَ {n} أشخاص', many: 'حظرتَ {n} شخصًا' },
    unblockAll: 'إلغاء حظر الجميع',
    guidelines: 'تُراجَع المنشورات قبل ظهورها. كن لطيفًا، ولا تشارك أبدًا تفاصيل خاصة عن أحد.',
  },
};
