// Builds Home's community map from Natural Earth (public domain) land data:
//   constants/worldLand.ts — the solid silhouette (one evenodd path)
//   constants/worldDots.ts — the halftone dot version + lat/lon projection
// Run: node scripts/world-map/build.js [--preview out.png]
//
// Source: ne_110m_land.geojson from github.com/nvkelso/natural-earth-vector
// (Natural Earth — "all versions … are in the public domain"; no credit needed).
const fs = require('fs');
const path = require('path');

const land = JSON.parse(fs.readFileSync(path.join(__dirname, 'ne_110m_land.geojson'), 'utf8'));
const OUT_LAND = path.join(__dirname, '../../constants/worldLand.ts');
const OUT_DOTS = path.join(__dirname, '../../constants/worldDots.ts');

// ── Projection: Miller cylindrical, centred so Alaska and Chukotka both fit ──
const VB_W = 200;
const LON_WEST = -169; // anything further west wraps to the east edge (Chukotka, Bering islands)
const LAT_TOP = 84; // northern Greenland
const LAT_BOTTOM = -57; // Cape Horn; Antarctica is left out
const rad = (d) => (d * Math.PI) / 180;
const millerY = (lat) => 1.25 * Math.log(Math.tan(Math.PI / 4 + 0.4 * rad(lat)));
const SCALE = VB_W / (2 * Math.PI); // viewBox units per radian of longitude
const Y_TOP = millerY(LAT_TOP);
const VB_H = +((Y_TOP - millerY(LAT_BOTTOM)) * SCALE).toFixed(1);
const wrapLon = (lon) => (lon < LON_WEST ? lon + 360 : lon);
const project = (lon, lat) => [((wrapLon(lon) - LON_WEST) / 360) * VB_W, (Y_TOP - millerY(lat)) * SCALE];

// ── Rings: drop Antarctica, wrap whole rings that sit west of the seam ──
const rings = [];
for (const f of land.features) {
  const polys = f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates;
  for (const poly of polys) {
    for (const ring of poly) {
      if (Math.max(...ring.map((p) => p[1])) < -60) continue; // Antarctica
      const allWest = ring.every((p) => p[0] < LON_WEST);
      rings.push(ring.map(([lon, lat]) => {
        const [x, y] = project(allWest ? lon : Math.max(lon, LON_WEST), lat);
        return [x, y];
      }));
    }
  }
}

// One pass of Chaikin smoothing softens the 1:110m data's straight runs
// toward the drawn look of the previous map, without changing its shapes.
function chaikin(pts) {
  const out = [];
  for (let i = 0; i < pts.length - 1; i++) {
    const [x0, y0] = pts[i];
    const [x1, y1] = pts[i + 1];
    out.push([0.75 * x0 + 0.25 * x1, 0.75 * y0 + 0.25 * y1], [0.25 * x0 + 0.75 * x1, 0.25 * y0 + 0.75 * y1]);
  }
  out.push(out[0]);
  return out;
}
const area = (pts) => Math.abs(pts.reduce((s, p, i) => { const q = pts[(i + 1) % pts.length]; return s + p[0] * q[1] - q[0] * p[1]; }, 0) / 2);

const f1 = (n) => Math.round(n * 10) / 10;
let d = '';
let kept = 0;
let points = 0;
const smooth = [];
for (const ring of rings) {
  if (area(ring) < 0.08) continue; // specks smaller than a dot
  const s = chaikin(ring);
  smooth.push(s);
  let px = f1(s[0][0]);
  let py = f1(s[0][1]);
  d += `M${px} ${py}`;
  for (let i = 1; i < s.length - 1; i++) {
    const x = f1(s[i][0]);
    const y = f1(s[i][1]);
    const rx = f1(x - px);
    const ry = f1(y - py);
    if (Math.abs(rx) < 0.35 && Math.abs(ry) < 0.35) continue; // steps under ~half a pixel on the card
    d += `l${rx} ${ry}`;
    px = x;
    py = y;
    points++;
  }
  d += 'z';
  kept++;
}

fs.writeFileSync(OUT_LAND, `/**
 * Solid-silhouette land for Home's community map (GENERATED by
 * scripts/world-map/build.js — do not edit by hand).
 *
 * Natural Earth 1:110m land (public domain), Miller projection, lat
 * ${LAT_TOP}° to ${LAT_BOTTOM}°, lightly smoothed: ${kept} outlines, ${points} points, in a
 * ${VB_W} × ${VB_H} viewBox. Render with \`fillRule="evenodd"\`. Same frame and
 * projection as worldDots.ts.
 */

export const WORLD_LAND_WIDTH = ${VB_W};
export const WORLD_LAND_HEIGHT = ${VB_H};

export const WORLD_LAND_PATH =
  '${d}';
`);

// ── Rasterise (even-odd scanline) for the halftone dots ──
const PX = 10; // mask pixels per viewBox unit
const W = VB_W * PX;
const H = Math.ceil(VB_H * PX);
const mask = new Uint8Array(W * H);
for (let y = 0; y < H; y++) {
  const sy = (y + 0.5) / PX;
  const xs = [];
  for (const ring of smooth) {
    for (let i = 0; i < ring.length - 1; i++) {
      const [x0, y0] = ring[i];
      const [x1, y1] = ring[i + 1];
      if ((y0 <= sy && y1 > sy) || (y1 <= sy && y0 > sy)) xs.push(x0 + ((sy - y0) / (y1 - y0)) * (x1 - x0));
    }
  }
  xs.sort((a, b) => a - b);
  for (let k = 0; k + 1 < xs.length; k += 2) {
    const a = Math.max(0, Math.ceil(xs[k] * PX - 0.5));
    const b = Math.min(W - 1, Math.floor(xs[k + 1] * PX - 0.5));
    for (let x = a; x <= b; x++) mask[y * W + x] = 1;
  }
}

const COLS = 88;
const pitch = W / COLS; // mask px
const rowPitch = (pitch * Math.sqrt(3)) / 2;
const ROWS = Math.floor(H / rowPitch);
const at = (x, y) => (x >= 0 && x < W && y >= 0 && y < H ? mask[y * W + x] : 0);
function coverage(cx, cy) {
  const r = pitch * 0.5;
  let n = 0;
  let hit = 0;
  const step = Math.max(1, Math.round(r / 5));
  for (let dy = -r; dy <= r; dy += step)
    for (let dx = -r; dx <= r; dx += step) {
      if (dx * dx + dy * dy > r * r) continue;
      n++;
      hit += at(Math.round(cx + dx), Math.round(cy + dy));
    }
  return hit / n;
}
const dots = [];
for (let r = 0; r < ROWS; r++) {
  const cy = rowPitch * (r + 0.5);
  const off = r % 2 ? pitch / 2 : 0;
  for (let c = 0; c < COLS; c++) {
    const cx = pitch * (c + 0.25) + off;
    const f = coverage(cx, cy);
    if (f < 0.2) continue;
    dots.push({ x: cx / PX, y: cy / PX, level: f > 0.75 ? 3 : f > 0.45 ? 2 : 1 });
  }
}
const R_MAX = (pitch * 0.3) / PX;
const f2 = (n) => +n.toFixed(2);
const RADII = [0, f2(R_MAX * 0.55), f2(R_MAX * 0.8), f2(R_MAX)];
const packed = dots.map((p) => `${Math.round(p.x * 10)},${Math.round(p.y * 10)},${p.level}`).join(',');

fs.writeFileSync(OUT_DOTS, `/**
 * Home's community map: projection + halftone dot version (GENERATED by
 * scripts/world-map/build.js — do not edit by hand).
 *
 * Natural Earth 1:110m land (public domain) in a Miller projection, the
 * same ${VB_W} × ${VB_H} frame as worldLand.ts. Dots sit on a staggered ${COLS}-column
 * grid, each sized by how much land it covers so coastlines taper like a
 * halftone screen; all ${dots.length} are one path.
 */

export const WORLD_DOTS_WIDTH = ${VB_W};
export const WORLD_DOTS_HEIGHT = ${VB_H};

/** Land dots packed as [x × 10, y × 10, size level 1–3, …] in viewBox units. */
const PACKED: readonly number[] = [${packed}];

const RADII = [${RADII.join(', ')}];

/** Dot centres, flat [x0, y0, x1, y1, …], for snapping markers onto land. */
export const WORLD_DOT_CENTRES: readonly number[] = PACKED.flatMap((v, i) => (i % 3 === 2 ? [] : [v / 10]));

/** Every land dot, as one SVG path (built once at load). */
export const WORLD_DOTS_PATH = (() => {
  let d = '';
  for (let i = 0; i < PACKED.length; i += 3) {
    const x = PACKED[i] / 10;
    const y = PACKED[i + 1] / 10;
    const r = RADII[PACKED[i + 2]];
    d += 'M' + (x - r) + ' ' + y + 'a' + r + ' ' + r + ' 0 1 0 ' + 2 * r + ' 0a' + r + ' ' + r + ' 0 1 0 ' + -2 * r + ' 0';
  }
  return d;
})();

/** Spacing between neighbouring dots, in viewBox units. */
export const WORLD_DOT_PITCH = ${f2(pitch / PX)};

const LON_WEST = ${LON_WEST};
const Y_TOP = ${Y_TOP};
const SCALE = ${SCALE};

/** Lat/lon to viewBox coordinates (Miller projection, the map's own). */
export function projectToMap(lat: number, lon: number): { x: number; y: number } {
  const wrapped = lon < LON_WEST ? lon + 360 : lon;
  const phi = (lat * Math.PI) / 180;
  const y = 1.25 * Math.log(Math.tan(Math.PI / 4 + 0.4 * phi));
  return { x: ((wrapped - LON_WEST) / 360) * ${VB_W}, y: (Y_TOP - y) * SCALE };
}

/**
 * The land dot nearest to a lat/lon, so a small country's marker still
 * lands on drawn land (tiny islands aren't in the 1:110m data). Falls back
 * to the raw projection when nothing is within a few dots.
 */
export function snapToLand(lat: number, lon: number): { x: number; y: number } {
  const p = projectToMap(lat, lon);
  let best = -1;
  let bestD = (WORLD_DOT_PITCH * 3) ** 2;
  for (let i = 0; i < WORLD_DOT_CENTRES.length; i += 2) {
    const dx = WORLD_DOT_CENTRES[i] - p.x;
    const dy = WORLD_DOT_CENTRES[i + 1] - p.y;
    const d2 = dx * dx + dy * dy;
    if (d2 < bestD) {
      bestD = d2;
      best = i;
    }
  }
  return best < 0 ? p : { x: WORLD_DOT_CENTRES[best], y: WORLD_DOT_CENTRES[best + 1] };
}
`);

console.log(`land: ${kept} outlines, ${points} points, ${(fs.statSync(OUT_LAND).size / 1024).toFixed(1)} KB; dots: ${dots.length}, ${(fs.statSync(OUT_DOTS).size / 1024).toFixed(1)} KB; viewBox ${VB_W}×${VB_H}`);

// Optional preview: the silhouette with a few capitals, for eyeballing.
const previewAt = process.argv.indexOf('--preview');
if (previewAt > 0) {
  const Jimp = require('jimp-compact');
  const img = new Jimp(W, H, 0xffffffff);
  for (let i = 0; i < W * H; i++) if (mask[i]) img.bitmap.data.writeUInt32BE(0x404058ff, i * 4);
  const TEST = [[51.5, -0.13], [24.7, 46.7], [30.0, 31.2], [35.7, 139.7], [-33.9, 151.2], [40.7, -74.0], [-12.0, -77.0], [-33.9, 18.4], [28.6, 77.2], [26.2, 50.6], [64.1, -21.9], [61.2, -149.9], [-6.2, 106.8], [-34.6, -58.4], [55.8, 37.6], [-41.3, 174.8]];
  for (const [lat, lon] of TEST) {
    const [x, y] = project(lon, lat);
    for (let dy = -12; dy <= 12; dy++) for (let dx = -12; dx <= 12; dx++) if (dx * dx + dy * dy <= 144) img.setPixelColor(0xe0303aff, Math.round(x * PX + dx), Math.round(y * PX + dy));
  }
  img.resize(1000, Jimp.AUTO).writeAsync(process.argv[previewAt + 1]).then(() => console.log('preview written'));
}
